<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Article;

class BlogArticleSeeder extends Seeder
{
    public function run(): void
    {
        $articles = [
            [
                'title' => 'PM Kisan Status Check 2025: How to Check Your Installment Status Online',
                'title_hi' => 'पीएम किसान स्टेटस चेक 2025: ऑनलाइन अपनी किस्त की स्थिति कैसे जांचें',
                'slug' => 'pm-kisan-status-check-2025-online',
                'content' => '<h2>PM Kisan Status Check 2025</h2><p>प्रधानमंत्री किसान सम्मान निधि योजना के तहत अब तक 18 से अधिक किस्तें जारी की जा चुकी हैं। अगर आप भी इस योजना के लाभार्थी हैं और अपनी अगली किस्त का स्टेटस जांचना चाहते हैं, तो यह गाइड आपके लिए है।</p><h3>PM Kisan किस्त स्टेटस ऑनलाइन कैसे चेक करें?</h3><ol><li>पीएम किसान की आधिकारिक वेबसाइट pmkisan.gov.in पर जाएं</li><li>होम पेज पर "Know Your Status" पर क्लिक करें</li><li>अपना रजिस्टर्ड मोबाइल नंबर या रजिस्ट्रेशन नंबर दर्ज करें</li><li>CAPTCHA कोड भरें और "Get OTP" पर क्लिक करें</li><li>OTP दर्ज करें और "Get Status" पर क्लिक करें</li></ol><h3>पीएम किसान किस्त की स्थिति समझें</h3><p>अगर आपका स्टेटस "Under Processing" दिखा रहा है तो घबराएं नहीं, इसका मतलब है कि आपकी किस्त प्रोसेसिंग में है। "FTO Generated" का मतलब है कि फंड ट्रांसफर ऑर्डर जनरेट हो चुका है और जल्द ही आपके खाते में पैसे आएंगे।</p><h3>पीएम किसान हेल्पलाइन नंबर</h3><p>अगर आपको कोई समस्या आ रही है तो टोल फ्री नंबर 1800115526 पर कॉल कर सकते हैं।</p>',
                'content_hi' => '<h2>पीएम किसान स्टेटस चेक 2025</h2><p>प्रधानमंत्री किसान सम्मान निधि योजना के तहत अब तक 18 से अधिक किस्तें जारी की जा चुकी हैं। अगर आप भी इस योजना के लाभार्थी हैं और अपनी अगली किस्त का स्टेटस जांचना चाहते हैं, तो यह गाइड आपके लिए है।</p><h3>पीएम किसान किस्त स्टेटस ऑनलाइन कैसे चेक करें?</h3><ol><li>पीएम किसान की आधिकारिक वेबसाइट pmkisan.gov.in पर जाएं</li><li>होम पेज पर "अपनी स्थिति जानें" पर क्लिक करें</li><li>अपना रजिस्टर्ड मोबाइल नंबर या रजिस्ट्रेशन नंबर दर्ज करें</li><li>CAPTCHA कोड भरें और "OTP प्राप्त करें" पर क्लिक करें</li><li>OTP दर्ज करें और "स्थिति प्राप्त करें" पर क्लिक करें</li></ol>',
                'excerpt' => 'Check your PM Kisan installment status online at pmkisan.gov.in. Step-by-step guide to track your ₹2,000 installment with registration number.',
                'excerpt_hi' => 'पीएम किसान किस्त का स्टेटस ऑनलाइन pmkisan.gov.in पर चेक करें। रजिस्ट्रेशन नंबर से अपनी ₹2,000 किस्त ट्रैक करने की चरण-दर-चरण मार्गदर्शिका।',
                'status' => 'published',
                'is_featured' => true,
                'published_at' => now()->subDays(3),
                'source_url' => 'https://pmkisan.gov.in',
            ],
            [
                'title' => 'Ayushman Bharat Card 2025: How to Download and Use for Free Treatment',
                'title_hi' => 'आयुष्मान भारत कार्ड 2025: मुफ्त इलाज के लिए कैसे डाउनलोड करें और उपयोग करें',
                'slug' => 'ayushman-bharat-card-download-2025',
                'content' => '<h2>आयुष्मान भारत कार्ड क्या है?</h2><p>आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (AB-PMJAY) के तहत पात्र परिवारों को ₹5 लाख तक का मुफ्त इलाज मिलता है। इस कार्ड के जरिए देश भर के 27,000 से अधिक अस्पतालों में कैशलेस इलाज ले सकते हैं।</p><h3>आयुष्मान कार्ड कैसे डाउनलोड करें?</h3><ol><li>अपने नजदीकी CSC (Common Service Centre) पर जाएं</li><li>अपना आधार कार्ड और राशन कार्ड लेकर जाएं</li><li>ऑपरेटर आपका eKYC करेगा और कार्ड प्रिंट करेगा</li><li>वैकल्पिक रूप से beneficiary.nhp.gov.in पर ऑनलाइन चेक कर सकते हैं</li></ol><h3>किन अस्पतालों में मिलता है इलाज?</h3><p>आयुष्मान भारत के तहत सरकारी और निजी दोनों तरह के अस्पताल शामिल हैं। आप अपने नजदीकी अस्पताल की जानकारी helpline number 14555 पर कॉल करके प्राप्त कर सकते हैं।</p>',
                'content_hi' => '<h2>आयुष्मान भारत कार्ड क्या है?</h2><p>आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना के तहत पात्र परिवारों को ₹5 लाख तक का मुफ्त इलाज मिलता है।</p>',
                'excerpt' => 'Download your Ayushman Bharat card and get free treatment worth ₹5 lakh at 27,000+ hospitals. Complete guide with download steps and hospital list.',
                'excerpt_hi' => 'अपना आयुष्मान भारत कार्ड डाउनलोड करें और 27,000+ अस्पतालों में ₹5 लाख तक का मुफ्त इलाज पाएं। डाउनलोड स्टेप्स और अस्पताल सूची के साथ पूरी गाइड।',
                'status' => 'published',
                'is_featured' => true,
                'published_at' => now()->subDays(5),
                'source_url' => 'https://pmjay.gov.in',
            ],
            [
                'title' => 'Ration Card Check Online 2025: How to Check Name in Ration Card List',
                'title_hi' => 'राशन कार्ड ऑनलाइन चेक 2025: राशन कार्ड लिस्ट में नाम कैसे देखें',
                'slug' => 'ration-card-check-online-2025-name-list',
                'content' => '<h2>राशन कार्ड लिस्ट में नाम कैसे देखें?</h2><p>राशन कार्ड भारत में सबसे महत्वपूर्ण दस्तावेजों में से एक है। इसके जरिए सस्ते दरों पर अनाज मिलता है। अगर आप अपना नाम राशन कार्ड लिस्ट में चेक करना चाहते हैं तो यह गाइड पढ़ें।</p><h3>ऑनलाइन राशन कार्ड लिस्ट कैसे देखें?</h3><ol><li>अपने राज्य के खाद्य विभाग की वेबसाइट पर जाएं</li><li>"राशन कार्ड लिस्ट" या "NFSA लाभार्थी सूची" पर क्लिक करें</li><li>अपना राज्य, जिला, तहसील और गांव/शहर चुनें</li><li>अपना राशन कार्ड नंबर या नाम खोजें</li></ol><h3>राशन कार्ड के प्रकार</h3><ul><li><strong>APL राशन कार्ड:</strong> गरीबी रेखा से ऊपर वाले परिवारों के लिए</li><li><strong>BPL राशन कार्ड:</strong> गरीबी रेखा से नीचे वाले परिवारों के लिए</li><li><strong>AAY राशन कार्ड:</strong> अंत्योदय अन्न योजना के तहत सबसे गरीब परिवारों के लिए</li></ul>',
                'content_hi' => '<h2>राशन कार्ड लिस्ट में नाम कैसे देखें?</h2><p>राशन कार्ड भारत में सबसे महत्वपूर्ण दस्तावेजों में से एक है।</p>',
                'excerpt' => 'Check your name in the ration card list online. Step-by-step guide to find your name in NFSA beneficiary list state-wise.',
                'excerpt_hi' => 'राशन कार्ड लिस्ट में अपना नाम ऑनलाइन चेक करें। राज्य-वार NFSA लाभार्थी सूची में अपना नाम खोजने की चरण-दर-चरण मार्गदर्शिका।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(7),
                'source_url' => 'https://nfsa.gov.in',
            ],
            [
                'title' => 'MGNREGA Job Card 2025: How to Apply and Check Job Card List',
                'title_hi' => 'मनरेगा जॉब कार्ड 2025: आवेदन कैसे करें और जॉब कार्ड लिस्ट चेक करें',
                'slug' => 'mnrega-job-card-apply-check-list-2025',
                'content' => '<h2>मनरेगा जॉब कार्ड क्या है?</h2><p>महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (MGNREGA) के तहत हर परिवार को साल में कम से कम 100 दिन का रोजगार मिलता है। जॉब कार्ड इस योजना का मुख्य दस्तावेज है।</p><h3>जॉब कार्ड के लिए आवेदन कैसे करें?</h3><ol><li>अपने ग्राम पंचायत कार्यालय में जाएं</li><li>जॉब कार्ड आवेदन फॉर्म भरें</li><li>आधार कार्ड, बैंक पासबुक और फोटो संलग्न करें</li><li>फॉर्म ग्राम सचिव को जमा करें</li></ol><h3>जॉब कार्ड लिस्ट कैसे चेक करें?</h3><p>nrega.nic.in पर जाकर अपना राज्य, जिला और ग्राम पंचायत चुनकर जॉब कार्ड लिस्ट देख सकते हैं।</p>',
                'content_hi' => '<h2>मनरेगा जॉब कार्ड क्या है?</h2><p>महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम के तहत हर परिवार को साल में कम से कम 100 दिन का रोजगार मिलता है।</p>',
                'excerpt' => 'Apply for MGNREGA job card and check the job card list online. Get 100 days guaranteed employment under MGNREGA scheme.',
                'excerpt_hi' => 'मनरेगा जॉब कार्ड के लिए आवेदन करें और जॉब कार्ड लिस्ट ऑनलाइन चेक करें। मनरेगा योजना के तहत 100 दिन की गारंटीशुदा रोजगार पाएं।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(10),
                'source_url' => 'https://nrega.nic.in',
            ],
            [
                'title' => 'PM Ujjwala Yojana 2025: Free LPG Connection - Apply Online',
                'title_hi' => 'पीएम उज्ज्वला योजना 2025: मुफ्त एलपीजी कनेक्शन - ऑनलाइन आवेदन',
                'slug' => 'pm-ujjwala-yojana-free-lpg-connection-2025',
                'content' => '<h2>पीएम उज्ज्वला योजना 2025</h2><p>प्रधानमंत्री उज्ज्वला योजना के तहत गरीबी रेखा से नीचे जीवन यापन करने वाले परिवारों को मुफ्त एलपीजी कनेक्शन दिया जाता है। इस योजना का उद्देश्य महिलाओं के स्वास्थ्य की रक्षा करना और प्रदूषण कम करना है।</p><h3>पात्रता मानदंड</h3><ul><li>महिला मुखिया वाला परिवार</li><li>BPL परिवार से संबंधित</li><li>18 वर्ष से अधिक आयु</li><li>एलपीजी कनेक्शन न हो</li></ul><h3>आवेदन प्रक्रिया</h3><p>नजदीकी एलपीजी डिपो या CSC केंद्र पर जाकर आवेदन कर सकते हैं। आधार कार्ड और BPL सूची में नाम होना जरूरी है।</p>',
                'content_hi' => '<h2>पीएम उज्ज्वला योजना 2025</h2><p>प्रधानमंत्री उज्ज्वला योजना के तहत गरीबी रेखा से नीचे जीवन यापन करने वाले परिवारों को मुफ्त एलपीजी कनेक्शन दिया जाता है।</p>',
                'excerpt' => 'Apply for free LPG connection under PM Ujjwala Yojana 2025. Check eligibility, documents required and application process.',
                'excerpt_hi' => 'पीएम उज्ज्वला योजना 2025 के तहत मुफ्त एलपीजी कनेक्शन के लिए आवेदन करें। पात्रता, आवश्यक दस्तावेज और आवेदन प्रक्रिया जांचें।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(12),
                'source_url' => 'https://www.pmujjwalayojana.com',
            ],
            [
                'title' => 'Jan Dhan Yojana 2025: Zero Balance Account and RuPay Card Benefits',
                'title_hi' => 'जन धन योजना 2025: जीरो बैलेंस खाता और रुपे कार्ड के लाभ',
                'slug' => 'jan-dhan-yojana-zero-balance-account-2025',
                'content' => '<h2>जन धन योजना क्या है?</h2><p>प्रधानमंत्री जन धन योजना के तहत देश का कोई भी नागरिक बिना किसी पैसे के बैंक खाता खोल सकता है। इस खाते में जीरो बैलेंस रखने की सुविधा है।</p><h3>जन धन खाते के लाभ</h3><ul><li>जीरो बैलेंस पर खाता खुलवाने की सुविधा</li><li>₹2 लाख का दुर्घटना बीमा कवर</li><li>₹30,000 का जीवन बीमा</li><li>रुपे डेबिट कार्ड की सुविधा</li><li>सरकारी योजनाओं का पैसा सीधे खाते में आता है</li></ul><h3>खाता कैसे खोलें?</h3><p>नजदीकी बैंक शाखा या CSP केंद्र पर आधार कार्ड और पासपोर्ट साइज फोटो लेकर जाएं।</p>',
                'content_hi' => '<h2>जन धन योजना क्या है?</h2><p>प्रधानमंत्री जन धन योजना के तहत देश का कोई भी नागरिक बिना किसी पैसे के बैंक खाता खोल सकता है।</p>',
                'excerpt' => 'Open a zero balance bank account under Jan Dhan Yojana. Get RuPay card, ₹2 lakh insurance and direct benefit transfer.',
                'excerpt_hi' => 'जन धन योजना के तहत जीरो बैलेंस बैंक खाता खोलें। रुपे कार्ड, ₹2 लाख बीमा और डायरेक्ट बेनिफिट ट्रांसफर पाएं।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(14),
                'source_url' => 'https://pmjdy.gov.in',
            ],
            [
                'title' => 'PM Kisan Samman Nidhi Yojana: Complete Guide in Hindi',
                'title_hi' => 'पीएम किसान सम्मान निधि योजना: हिंदी में पूरी जानकारी',
                'slug' => 'pm-kisan-samman-nidhi-yojana-complete-guide-hindi',
                'content' => '<h2>पीएम किसान सम्मान निधि योजना</h2><p>प्रधानमंत्री किसान सम्मान निधि योजना भारत सरकार की एक महत्वपूर्ण योजना है जो देश भर के किसानों को आर्थिक सहायता प्रदान करती है। इस योजना के तहत हर साल ₹6,000 तीन किस्तों में दिए जाते हैं।</p><h3>मुख्य लाभ</h3><ul><li>साल में ₹6,000 की आर्थिक सहायता</li><li>तीन किस्तों में ₹2,000 प्रति किस्त</li><li>सीधे बैंक खाते में ट्रांसफर</li><li>कोई मध्यस्थ नहीं</li></ul><h3>पात्रता</h3><p>सभी भूमिधारक किसान परिवार इस योजना के पात्र हैं। आयकर दाता, सरकारी कर्मचारी और पेंशनभोगी इस योजना के पात्र नहीं हैं।</p>',
                'content_hi' => '<h2>पीएम किसान सम्मान निधि योजना</h2><p>प्रधानमंत्री किसान सम्मान निधि योजना भारत सरकार की एक महत्वपूर्ण योजना है।</p>',
                'excerpt' => 'Complete guide to PM Kisan Samman Nidhi Yojana in Hindi. ₹6,000 annual support for farmers with eligibility and application details.',
                'excerpt_hi' => 'पीएम किसान सम्मान निधि योजना की हिंदी में पूरी जानकारी। किसानों के लिए ₹6,000 वार्षिक सहायता, पात्रता और आवेदन विवरण।',
                'status' => 'published',
                'is_featured' => true,
                'published_at' => now()->subDays(1),
                'source_url' => 'https://pmkisan.gov.in',
            ],
            [
                'title' => 'Soil Health Card Scheme 2025: How to Get Your Soil Tested',
                'title_hi' => 'मृदा स्वास्थ्य कार्ड योजना 2025: अपनी मिट्टी की जांच कैसे कराएं',
                'slug' => 'soil-health-card-scheme-get-tested-2025',
                'content' => '<h2>मृदा स्वास्थ्य कार्ड योजना</h2><p>मृदा स्वास्थ्य कार्ड योजना किसानों को उनकी मिट्टी की गुणवत्ता के बारे में जानकारी देती है। इस कार्ड के जरिए किसान जान सकते हैं कि उनकी मिट्टी में कौन से पोषक तत्वों की कमी है।</p><h3>मिट्टी की जांच कैसे कराएं?</h3><ol><li>अपने नजदीकी कृषि केंद्र पर जाएं</li><li>मिट्टी का नमूना दें</li><li>2-3 हफ्ते में रिपोर्ट मिलेगी</li><li>ऑनलाइन soilhealth.dac.gov.in पर भी चेक कर सकते हैं</li></ol>',
                'content_hi' => '<h2>मृदा स्वास्थ्य कार्ड योजना</h2><p>मृदा स्वास्थ्य कार्ड योजना किसानों को उनकी मिट्टी की गुणवत्ता के बारे में जानकारी देती है।</p>',
                'excerpt' => 'Get your soil tested under Soil Health Card Scheme. Know nutrient deficiencies and get fertilizer recommendations for better crop yield.',
                'excerpt_hi' => 'मृदा स्वास्थ्य कार्ड योजना के तहत अपनी मिट्टी की जांच कराएं। पोषक तत्वों की कमी जानें और बेहतर फसल के लिए खाद सिफारिश पाएं।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(16),
                'source_url' => 'https://soilhealth.dac.gov.in',
            ],
            [
                'title' => 'Skill India Registration 2025: Free Vocational Training for Youth',
                'title_hi' => 'स्किल इंडिया रजिस्ट्रेशन 2025: युवाओं के लिए मुफ्त व्यावसायिक प्रशिक्षण',
                'slug' => 'skill-india-registration-free-vocational-training-2025',
                'content' => '<h2>स्किल इंडिया क्या है?</h2><p>स्किल इंडिया मिशन का उद्देश्य भारतीय युवाओं को कौशल प्रदान करना है ताकि वे रोजगार या स्वरोजगार के लिए तैयार हो सकें।</p><h3>पंजीकरण कैसे करें?</h3><ol><li>skillindia.nsdcindia.org पर जाएं</li><li>"Register Now" पर क्लिक करें</li><li>अपनी जानकारी भरें</li><li>अपना कोर्स चुनें</li><li>नजदीकी प्रशिक्षण केंद्र में जाएं</li></ol>',
                'content_hi' => '<h2>स्किल इंडिया क्या है?</h2><p>स्किल इंडिया मिशन का उद्देश्य भारतीय युवाओं को कौशल प्रदान करना है।</p>',
                'excerpt' => 'Register for free vocational training under Skill India Mission. Get certified courses in IT, healthcare, tourism and more.',
                'excerpt_hi' => 'स्किल इंडिया मिशन के तहत मुफ्त व्यावसायिक प्रशिक्षण के लिए पंजीकरण करें। IT, स्वास्थ्य, पर्यटन में प्रमाणित कोर्स पाएं।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(18),
                'source_url' => 'https://skillindia.nsdcindia.org',
            ],
            [
                'title' => 'Swachh Bharat Mission 2025: Toilet Subsidy and Clean India Campaign',
                'title_hi' => 'स्वच्छ भारत मिशन 2025: शौचालय सब्सिडी और स्वच्छ भारत अभियान',
                'slug' => 'swachh-bharat-mission-toilet-subsidy-2025',
                'content' => '<h2>स्वच्छ भारत मिशन</h2><p>स्वच्छ भारत मिशन का उद्देश्य भारत को खुले में शौच मुक्त बनाना है। इस योजना के तहत गरीब परिवारों को शौचालय बनाने के लिए सब्सिडी दी जाती है।</p><h3>शौचालय सब्सिडी कैसे मिलेगी?</h3><ol><li>अपने ग्राम पंचायत कार्यालय में आवेदन करें</li><li>₹12,000 की सब्सिडी मिलती है</li><li>शौचालय बनने के बाद फोटो और बिल जमा करें</li><li>सब्सिडी सीधे बैंक खाते में आएगी</li></ol>',
                'content_hi' => '<h2>स्वच्छ भारत मिशन</h2><p>स्वच्छ भारत मिशन का उद्देश्य भारत को खुले में शौच मुक्त बनाना है।</p>',
                'excerpt' => 'Get ₹12,000 subsidy for toilet construction under Swachh Bharat Mission. Complete guide to apply and check status.',
                'excerpt_hi' => 'स्वच्छ भारत मिशन के तहत शौचालय निर्माण के लिए ₹12,000 सब्सिडी पाएं। आवेदन और स्थिति जांचने की पूरी गाइड।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(20),
                'source_url' => 'https://sbm.gov.in',
            ],
            [
                'title' => 'Digital India Initiative 2025: Government Services Going Online',
                'title_hi' => 'डिजिटल इंडिया पहल 2025: सरकारी सेवाएं ऑनलाइन',
                'slug' => 'digital-india-initiative-government-services-online-2025',
                'content' => '<h2>डिजिटल इंडिया क्या है?</h2><p>डिजिटल इंडिया भारत सरकार की एक पहल है जिसका उद्देश्य सरकारी सेवाओं को डिजिटल माध्यम से नागरिकों तक पहुंचाना है।</p><h3>मुख्य सेवाएं</h3><ul><li>आधार कार्ड अपडेट</li><li>पैन कार्ड ऑनलाइन आवेदन</li><li>पासपोर्ट ऑनलाइन आवेदन</li><li>वोटर आईडी ऑनलाइन सुधार</li></ul>',
                'content_hi' => '<h2>डिजिटल इंडिया क्या है?</h2><p>डिजिटल इंडिया भारत सरकार की एक पहल है।</p>',
                'excerpt' => 'Learn about Digital India initiative and access government services online. Apply for Aadhaar, PAN, Passport and more digitally.',
                'excerpt_hi' => 'डिजिटल इंडिया पहल के बारे में जानें और सरकारी सेवाओं को ऑनलाइन एक्सेस करें। आधार, पैन, पासपोर्ट के लिए डिजिटल रूप से आवेदन करें।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(22),
                'source_url' => 'https://digitalindia.gov.in',
            ],
            [
                'title' => 'Startup India Registration 2025: How to Register Your Startup',
                'title_hi' => 'स्टार्टअप इंडिया रजिस्ट्रेशन 2025: अपना स्टार्टअप कैसे रजिस्टर करें',
                'slug' => 'startup-india-registration-how-to-register-2025',
                'content' => '<h2>स्टार्टअप इंडिया क्या है?</h2><p>स्टार्टअप इंडिया भारत सरकार की एक पहल है जो उद्यमियों को अपना व्यवसाय शुरू करने में मदद करती है।</p><h3>रजिस्ट्रेशन कैसे करें?</h3><ol><li>startupindia.gov.in पर जाएं</li><li>"Register Your Startup" पर क्लिक करें</li><li>DPIIT recognition के लिए आवेदन करें</li><li>टैक्स बेनिफिट और फंडिंग का लाभ उठाएं</li></ol>',
                'content_hi' => '<h2>स्टार्टअप इंडिया क्या है?</h2><p>स्टार्टअप इंडिया भारत सरकार की एक पहल है।</p>',
                'excerpt' => 'Register your startup under Startup India and get tax benefits, funding support and DPIIT recognition.',
                'excerpt_hi' => 'स्टार्टअप इंडिया के तहत अपना स्टार्टअप रजिस्टर करें और टैक्स बेनिफिट, फंडिंग सपोर्ट और DPIIT मान्यता पाएं।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(24),
                'source_url' => 'https://startupindia.gov.in',
            ],
            [
                'title' => 'Make in India 2025: Benefits for Manufacturing Sector',
                'title_hi' => 'मेक इन इंडिया 2025: विनिर्माण क्षेत्र के लिए लाभ',
                'slug' => 'make-in-india-benefits-manufacturing-sector-2025',
                'content' => '<h2>मेक इन इंडिया क्या है?</h2><p>मेक इन इंडिया भारत को विनिर्माण का हब बनाने की पहल है। इसका उद्देश्य विदेशी निवेश को आकर्षित करना और रोजगार पैदा करना है।</p><h3>मुख्य लाभ</h3><ul><li>100% FDI की अनुमति</li><li>सरलीकृत नियम और कानून</li><li>बुनियादी ढांचे का विकास</li><li>रोजगार के अवसर</li></ul>',
                'content_hi' => '<h2>मेक इन इंडिया क्या है?</h2><p>मेक इन इंडिया भारत को विनिर्माण का हब बनाने की पहल है।</p>',
                'excerpt' => 'Learn about Make in India benefits for manufacturing. 100% FDI allowed, simplified regulations and infrastructure development.',
                'excerpt_hi' => 'विनिर्माण क्षेत्र के लिए मेक इन इंडिया लाभ जानें। 100% FDI की अनुमति, सरलीकृत नियम और बुनियादी ढांचे का विकास।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(26),
                'source_url' => 'https://www.makeinindia.com',
            ],
            [
                'title' => 'Smart Cities Mission 2025: Top 100 Cities Development Project',
                'title_hi' => 'स्मार्ट सिटी मिशन 2025: शीर्ष 100 शहरों का विकास परियोजना',
                'slug' => 'smart-cities-mission-100-cities-development-2025',
                'content' => '<h2>स्मार्ट सिटी मिशन क्या है?</h2><p>स्मार्ट सिटी मिशन का उद्देश्य 100 शहरों को स्मार्ट बनाना है। इन शहरों में बेहतर बुनियादी ढांचा, डिजिटल सेवाएं और हरित क्षेत्र होंगे।</p><h3>स्मार्ट सिटी की विशेषताएं</h3><ul><li>डिजिटल गवर्नेंस</li><li>स्मार्ट पानी और बिजली प्रबंधन</li><li>ICT आधारित यातायात प्रबंधन</li><li>हरित भवन और सौर ऊर्जा</li></ul>',
                'content_hi' => '<h2>स्मार्ट सिटी मिशन क्या है?</h2><p>स्मार्ट सिटी मिशन का उद्देश्य 100 शहरों को स्मार्ट बनाना है।</p>',
                'excerpt' => 'Smart Cities Mission aims to develop 100 cities with smart infrastructure, digital governance and green spaces.',
                'excerpt_hi' => 'स्मार्ट सिटी मिशन का उद्देश्य 100 शहरों को स्मार्ट बुनियादी ढांचा, डिजिटल गवर्नेंस और हरित क्षेत्रों के साथ विकसित करना है।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(28),
                'source_url' => 'https://smartcities.gov.in',
            ],
            [
                'title' => 'PM Awas Yojana Gramin 2025: Apply for Free House in Village',
                'title_hi' => 'पीएम आवास योजना ग्रामीण 2025: गांव में मुफ्त घर के लिए आवेदन',
                'slug' => 'pm-awas-yojana-gramin-free-house-2025',
                'content' => '<h2>पीएम आवास योजना ग्रामीण</h2><p>प्रधानमंत्री आवास योजना ग्रामीण के तहत गांवों में पक्के घर बनाने के लिए सहायता दी जाती है।</p><h3>पात्रता</h3><ul><li>BPL परिवार</li><li>बेघर या कच्चे घर में रहने वाले</li><li>SC/ST और अल्पसंख्यकों को प्राथमिकता</li></ul><h3>सहायता राशि</h3><p>मैदानी क्षेत्रों में ₹1,20,000 और पहाड़ी क्षेत्रों में ₹1,30,000 की सहायता दी जाती है।</p>',
                'content_hi' => '<h2>पीएम आवास योजना ग्रामीण</h2><p>प्रधानमंत्री आवास योजना ग्रामीण के तहत गांवों में पक्के घर बनाने के लिए सहायता दी जाती है।</p>',
                'excerpt' => 'Apply for PM Awas Yojana Gramin to get ₹1.2 lakh for building a pucca house in rural areas. Check eligibility and apply now.',
                'excerpt_hi' => 'ग्रामीण क्षेत्रों में पक्का घर बनाने के लिए ₹1.2 लाख पाने के लिए पीएम आवास योजना ग्रामीण के लिए आवेदन करें। पात्रता जांचें और अभी आवेदन करें।',
                'status' => 'published',
                'is_featured' => true,
                'published_at' => now()->subDays(4),
                'source_url' => 'https://pmayg.nic.in',
            ],
            [
                'title' => 'Atal Pension Yojana 2025: Pension Plan for Unorganized Sector Workers',
                'title_hi' => 'अटल पेंशन योजना 2025: असंगठित क्षेत्र के श्रमिकों के लिए पेंशन योजना',
                'slug' => 'atal-pension-yojana-pension-plan-unorganized-2025',
                'content' => '<h2>अटल पेंशन योजना</h2><p>अटल पेंशन योजना असंगठित क्षेत्र के श्रमिकों के लिए एक पेंशन योजना है। 18 से 40 वर्ष की आयु के बीच कोई भी व्यक्ति इस योजना में शामिल हो सकता है।</p><h3>पेंशन विकल्प</h3><ul><li>₹1,000 प्रति माह पेंशन</li><li>₹2,000 प्रति माह पेंशन</li><li>₹3,000 प्रति माह पेंशन</li><li>₹4,000 प्रति माह पेंशन</li><li>₹5,000 प्रति माह पेंशन</li></ul>',
                'content_hi' => '<h2>अटल पेंशन योजना</h2><p>अटल पेंशन योजना असंगठित क्षेत्र के श्रमिकों के लिए एक पेंशन योजना है।</p>',
                'excerpt' => 'Join Atal Pension Yojana for guaranteed pension of ₹1,000 to ₹5,000 per month. Age 18-40 years eligible.',
                'excerpt_hi' => 'अटल पेंशन योजना में शामिल हों और ₹1,000 से ₹5,000 प्रति माह गारंटीशुदा पेंशन पाएं। आयु 18-40 वर्ष पात्र।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(30),
                'source_url' => 'https://www.npscra.nsdl.co.in',
            ],
            [
                'title' => 'Sukanya Samriddhi Yojana 2025: Best Savings Scheme for Girl Child',
                'title_hi' => 'सुकन्या समृद्धि योजना 2025: बेटी के लिए सबसे अच्छी बचत योजना',
                'slug' => 'sukanya-samriddhi-yojana-best-savings-girl-child-2025',
                'content' => '<h2>सुकन्या समृद्धि योजना</h2><p>सुकन्या समृद्धि योजना बेटियों के लिए एक बेहतरीन बचत योजना है। इसमें 8.2% ब्याज मिलता है और टैक्स छूट भी मिलती है।</p><h3>मुख्य विशेषताएं</h3><ul><li>10 वर्ष से कम आयु की बेटी के लिए खाता खोला जा सकता है</li><li>साल में ₹250 से ₹1.5 लाख तक जमा कर सकते हैं</li><li>8.2% ब्याज दर (वार्षिक)</li><li>टैक्स अंडर 80C में छूट</li></ul>',
                'content_hi' => '<h2>सुकन्या समृद्धि योजना</h2><p>सुकन्या समृद्धि योजना बेटियों के लिए एक बेहतरीन बचत योजना है।</p>',
                'excerpt' => 'Open Sukanya Samriddhi account for your daughter and get 8.2% interest with tax benefits. Best savings scheme for girl child.',
                'excerpt_hi' => 'अपनी बेटी के लिए सुकन्या समृद्धि खाता खोलें और टैक्स लाभ के साथ 8.2% ब्याज पाएं। बेटी के लिए सबसे अच्छी बचत योजना।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(32),
                'source_url' => 'https://www.indiapost.gov.in',
            ],
            [
                'title' => 'National Pension Scheme (NPS) 2025: Government Pension Scheme Explained',
                'title_hi' => 'राष्ट्रीय पेंशन योजना (NPS) 2025: सरकारी पेंशन योजना की जानकारी',
                'slug' => 'national-pension-scheme-nps-government-explained-2025',
                'content' => '<h2>राष्ट्रीय पेंशन योजना</h2><p>NPS एक वैकल्पिक पेंशन योजना है जो सरकारी और निजी दोनों क्षेत्र के कर्मचारियों के लिए उपलब्ध है।</p><h3>NPS के फायदे</h3><ul><li>60 साल की उम्र के बाद पेंशन</li><li>टैक्स अंडर 80CCD(1B) में ₹50,000 की अतिरिक्त छूट</li><li>बाजार-आधारित रिटर्न</li><li>कम एक्सपेंस रेश्यो</li></ul>',
                'content_hi' => '<h2>राष्ट्रीय पेंशन योजना</h2><p>NPS एक वैकल्पिक पेंशन योजना है।</p>',
                'excerpt' => 'Join National Pension Scheme for retirement planning. Get tax benefits under 80CCD(1B) and market-linked returns.',
                'excerpt_hi' => 'सेवानिवृत्ति योजना के लिए राष्ट्रीय पेंशन योजना में शामिल हों। 80CCD(1B) के तहत टैक्स लाभ और बाजार-आधारित रिटर्न पाएं।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(34),
                'source_url' => 'https://www.npscra.nsdl.co.in',
            ],
            [
                'title' => 'LPG Subsidy Status 2025: Check Your Gas Cylinder Subsidy Online',
                'title_hi' => 'एलपीजी सब्सिडी स्टेटस 2025: अपनी गैस सिलेंडर सब्सिडी ऑनलाइन चेक करें',
                'slug' => 'lpg-subsidy-status-check-gas-cylinder-2025',
                'content' => '<h2>एलपीजी सब्सिडी स्टेटस कैसे चेक करें?</h2><p>अगर आप एलपीजी गैस कनेक्शन धारक हैं तो आप अपनी सब्सिडी का स्टेटस ऑनलाइन चेक कर सकते हैं।</p><h3>स्टेटस चेक करने के तरीके</h3><ol><li>mylpg.in पर जाएं</li><li>अपनी कंपनी (HP, Bharat, Indane) चुनें</li><li>अपना मोबाइल नंबर दर्ज करें</li><li>सब्सिडी हिस्ट्री देखें</li></ol>',
                'content_hi' => '<h2>एलपीजी सब्सिडी स्टेटस कैसे चेक करें?</h2><p>अगर आप एलपीजी गैस कनेक्शन धारक हैं।</p>',
                'excerpt' => 'Check your LPG gas cylinder subsidy status online at mylpg.in. Track DBT subsidy credit in your bank account.',
                'excerpt_hi' => 'mylpg.in पर अपनी एलपीजी गैस सिलेंडर सब्सिडी की स्थिति ऑनलाइन चेक करें। अपने बैंक खाते में DBT सब्सिडी क्रेडिट ट्रैक करें।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(36),
                'source_url' => 'https://www.myLPG.in',
            ],
            [
                'title' => 'Scholarship Status Check 2025: NSP Portal Login and Application Status',
                'title_hi' => 'छात्रवृत्ति स्टेटस चेक 2025: NSP पोर्टल लॉगिन और आवेदन स्थिति',
                'slug' => 'scholarship-status-check-nsp-portal-login-2025',
                'content' => '<h2>NSP पर छात्रवृत्ति स्टेटस कैसे चेक करें?</h2><p>राष्ट्रीय छात्रवृत्ति पोर्टल (NSP) पर आवेदन करने के बाद आप अपना स्टेटस ऑनलाइन चेक कर सकते हैं।</p><h3>स्टेटस चेक करने के चरण</h3><ol><li>scholarships.gov.in पर जाएं</li><li>"Track Your Status" पर क्लिक करें</li><li>अपना Application ID और पासवर्ड दर्ज करें</li><li>स्टेटस देखें</li></ol>',
                'content_hi' => '<h2>NSP पर छात्रवृत्ति स्टेटस कैसे चेक करें?</h2><p>राष्ट्रीय छात्रवृत्ति पोर्टल पर आवेदन करने के बाद।</p>',
                'excerpt' => 'Check your scholarship application status on NSP portal. Login with Application ID and track your scholarship payment.',
                'excerpt_hi' => 'NSP पोर्टल पर अपनी छात्रवृत्ति आवेदन स्थिति जांचें। Application ID से लॉगिन करें और छात्रवृत्ति भुगतान ट्रैक करें।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(38),
                'source_url' => 'https://scholarships.gov.in',
            ],
            [
                'title' => 'GST Registration 2025: How to Register for GST Online in India',
                'title_hi' => 'जीएसटी रजिस्ट्रेशन 2025: भारत में ऑनलाइन जीएसटी के लिए कैसे रजिस्टर करें',
                'slug' => 'gst-registration-online-india-2025',
                'content' => '<h2>जीएसटी रजिस्ट्रेशन</h2><p>जीएसटी (Goods and Services Tax) में रजिस्ट्रेशन उन सभी व्यवसायों के लिए जरूरी है जिनका सालाना टर्नओवर ₹40 लाख से अधिक है।</p><h3>रजिस्ट्रेशन कैसे करें?</h3><ol><li>gst.gov.in पर जाएं</li><li>"Services" > "Registration" > "New Registration" पर क्लिक करें</li><li>PAN, आधार और व्यवसाय की जानकारी भरें</li><li>दस्तावेज अपलोड करें</li><li>ARN नंबर प्राप्त करें</li></ol>',
                'content_hi' => '<h2>जीएसटी रजिस्ट्रेशन</h2><p>जीएसटी में रजिस्ट्रेशन उन सभी व्यवसायों के लिए जरूरी है।</p>',
                'excerpt' => 'Register for GST online at gst.gov.in. Complete guide for businesses with turnover above ₹40 lakh.',
                'excerpt_hi' => 'gst.gov.in पर ऑनलाइन जीएसटी के लिए रजिस्टर करें। ₹40 लाख से अधिक टर्नओवर वाले व्यवसायों के लिए पूरी गाइड।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(40),
                'source_url' => 'https://gst.gov.in',
            ],
            [
                'title' => 'PMAY 2025: Home Loan Subsidy under Credit Linked Subsidy Scheme',
                'title_hi' => 'पीएमएवाई 2025: क्रेडिट लिंक्ड सब्सिडी योजना के तहत होम लोन सब्सिडी',
                'slug' => 'pmay-2025-home-loan-subsidy-credit-linked-scheme',
                'content' => '<h2>प्रधानमंत्री आवास योजना (क्रेडिट लिंक्ड सब्सिडी योजना)</h2><p>PMAY के तहत पहली बार घर खरीदने वाले लोगों को ब्याज पर सब्सिडी मिलती है। सरकार ने एमटीएम ब्याज दरों में 1.2% से 2.67% तक की सब्सिडी की घोषणा की है।</p><h3>सब्सिडी के लिए पात्रता</h3><ul><li>आय ₹3 लाख से अधिक नहीं होनी चाहिए</li><li>पहली बार घर खरीदने वाला व्यक्ति</li><li>ग्राहक की आयु 21-60 वर्ष होनी चाहिए</li></ul><h3>कैसे मिलती है सब्सिडी</h3><p>सब्सिडी को लागू एमटीएम ब्याज दर और निश्चित बैंक दरों के बीच के अंतर में दी जाती है। सब्सिडी की राशि ऋण राशि के प्रतिशत के रूप में व्यक्त की जाती है।</p>',
                'content_hi' => '<h2>प्रधानमंत्री आवास योजना (क्रेडिट लिंक्ड सब्सिडी योजना)</h2><p>PMAY के तहत पहली बार घर खरीदने वाले लोगों को ब्याज पर सब्सिडी मिलती है। सरकार ने एमटीएम ब्याज दरों में 1.2% से 2.67% तक की सब्सिडी की घोषणा की है।</p>',
                'excerpt' => 'Get home loan subsidy under PMAY 2025 CLSS scheme. Up to 2.67% interest subsidy for first-time homebuyers.',
                'excerpt_hi' => 'पीएमएवाई 2025 क्रेडिट लिंक्ड सब्सिडी योजना के तहत होम लोन सब्सिडी पाएं। पहली बार घर खरीदारों को 2.67% तक ब्याज सब्सिडी।',
                'status' => 'published',
                'is_featured' => false,
                'published_at' => now()->subDays(42),
                'source_url' => 'https://pmay.gov.in',
            ],
        ];

        foreach ($articles as $article) {
            Article::create($article);
        }

        $this->command->info("BlogArticleSeeder: " . count($articles) . " blog articles created.");
    }
}
