<?php

namespace Database\Seeders;

use App\Models\Scheme;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ExpandedSchemeSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::pluck('id', 'slug');
        
        $schemes = [
            // ===== EDUCATION (20 schemes) =====
            [
                'category_slug' => 'education',
                'title' => 'PM SHRI Schools',
                'title_hi' => 'पीएम श्री विद्यालय',
                'slug' => 'pm-shri-schools',
                'short_description' => 'Exemplar schools for quality education with modern infrastructure and technology.',
                'short_description_hi' => 'आधुनिक बुनियादी ढांचे और प्रौद्योगिकी के साथ गुणवत्तापूर्ण शिक्षा के लिए आदर्श विद्यालय।',
                'status' => 'active',
                'is_featured' => true,
                'official_website' => 'https://pmshri.education.gov.in',
                'eligibility' => '• Government schools at primary, upper primary and secondary level\n• Schools run by government, local bodies, and aided schools\n• Schools must have UDISE code',
                'eligibility_hi' => '• प्राथमिक, उच्च प्राथमिक और माध्यमिक स्तर के सरकारी विद्यालय\n• सरकारी, स्थानीय निकायों और सहायता प्राप्त विद्यालय\n• विद्यालय के पास UDISE कोड होना चाहिए',
                'benefits' => '• Smart classrooms and labs\n• Digital learning resources\n• Teacher training programs\n• Improved infrastructure\n• ₹25-50 lakh per school',
                'benefits_hi' => '• स्मार्ट क्लासरूम और प्रयोगशालाएं\n• डिजिटल शिक्षा संसाधन\n• शिक्षक प्रशिक्षण कार्यक्रम\n• बेहतर बुनियादी ढांचा\n• ₹25-50 लाख प्रति विद्यालय',
                'application_process' => '1. School applies through state education department\n2. Selection based on infrastructure criteria\n3. MoU signed with DOE\n4. Funds released',
                'application_process_hi' => '1. विद्यालय राज्य शिक्षा विभाग के माध्यम से आवेदन करता है\n2. बुनियादी ढांचे के मानदंडों के आधार पर चयन\n3. DOE के साथ MoU पर हस्ताक्षर\n4. धनराशि जारी',
                'required_documents' => 'UDISE code, school infrastructure details, enrollment data',
                'required_documents_hi' => 'UDISE कोड, विद्यालय बुनियादी ढांचा विवरण, नामांकन डेटा',
                'content' => '<h2>PM SHRI Schools</h2><p>PM SHRI (Schools for Rising India) is a centrally sponsored scheme to develop 14,500 schools as exemplar institutions.</p><p>The scheme aims to implement NEP 2020 and provide quality education with modern pedagogy.</p>',
                'content_hi' => '<h2>पीएम श्री विद्यालय</h2><p>पीएम श्री (स्कूल्स फॉर राइजिंग इंडिया) एक केंद्रीय प्रायोजित योजना है जो 14,500 विद्यालयों को आदर्श संस्थानों के रूप में विकसित करती है।</p><p>यह योजना NEP 2020 को लागू करने और आधुनिक शिक्षण विधियों के साथ गुणवत्तापूर्ण शिक्षा प्रदान करने का लक्ष्य रखती है।</p>',
                'meta_title' => 'PM SHRI Schools - NEP 2020 Implementation | UmangIndia',
                'meta_title_hi' => 'पीएम श्री विद्यालय - NEP 2020 कार्यान्वयन | UmangIndia',
                'meta_description' => 'PM SHRI Schools scheme - 14,500 exemplar schools with modern infrastructure under NEP 2020.',
                'meta_description_hi' => 'पीएम श्री विद्यालय योजना - NEP 2020 के तहत आधुनिक बुनियादी ढांचे वाले 14,500 आदर्श विद्यालय।',
                'meta_keywords' => 'PM SHRI Schools, NEP 2020, school education India',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Atal Tinkering Labs',
                'title_hi' => 'अटल टिंकरिंग लैब्स',
                'slug' => 'atal-tinkering-labs',
                'short_description' => 'Innovation labs in schools for STEM learning and hands-on experiments.',
                'short_description_hi' => 'STEM शिक्षा और प्रयोगात्मक प्रयोगों के लिए विद्यालयों में नवाचार प्रयोगशालाएं।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://atalinnovationmission.gov.in',
                'eligibility' => '• Government and government-aided schools\n• Classes 6-12\n• Schools with minimum 100 students',
                'eligibility_hi' => '• सरकारी और सहायता प्राप्त विद्यालय\n• कक्षा 6-12\n• कम से कम 100 छात्रों वाले विद्यालय',
                'benefits' => '• ₹20 lakh per lab setup\n• STEM equipment and tools\n• Training for teachers\n• Annual operational funds',
                'benefits_hi' => '• ₹20 लाख प्रति लैब सेटअप\n• STEM उपकरण और औजार\n• शिक्षकों के लिए प्रशिक्षण\n• वार्षिक संचालन निधि',
                'application_process' => '1. School principal applies online\n2. Selection by state-level committee\n3. Lab setup with ATL equipment\n4. Teacher training begins',
                'application_process_hi' => '1. विद्यालय प्रधानाचार्य ऑनलाइन आवेदन करते हैं\n2. राज्य स्तरीय समिति द्वारा चयन\n3. ATL उपकरणों के साथ लैब सेटअप\n4. शिक्षक प्रशिक्षण शुरू',
                'required_documents' => 'School UDISE code, principal approval, student enrollment data',
                'required_documents_hi' => 'विद्यालय UDISE कोड, प्रधानाचार्य अनुमोदन, छात्र नामांकन डेटा',
                'content' => '<h2>Atal Tinkering Labs</h2><p>Atal Innovation Mission (AIM) establishes Atal Tinkering Labs in schools to foster curiosity and innovation among students.</p>',
                'content_hi' => '<h2>अटल टिंकरिंग लैब्स</h2><p>अटल नवोन्मेश मिशन (AIM) छात्रों में जिज्ञासा और नवाचार को बढ़ावा देने के लिए विद्यालयों में अटल टिंकरिंग लैब स्थापित करता है।</p>',
                'meta_title' => 'Atal Tinkering Labs - STEM Innovation | UmangIndia',
                'meta_title_hi' => 'अटल टिंकरिंग लैब्स - STEM नवाचार | UmangIndia',
                'meta_description' => 'Atal Tinkering Labs - Innovation labs in schools for STEM learning.',
                'meta_description_hi' => 'अटल टिंकरिंग लैब्स - STEM शिक्षा के लिए विद्यालयों में नवाचार प्रयोगशालाएं।',
                'meta_keywords' => 'Atal Tinkering Labs, STEM, innovation, AIM',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'National Digital Literacy Mission',
                'title_hi' => 'राष्ट्रीय डिजिटल साक्षरता मिशन',
                'slug' => 'national-digital-literacy-mission',
                'short_description' => 'Free digital literacy training for citizens to use computers, tablets and internet.',
                'short_description_hi' => 'नागरिकों को कंप्यूटर, टैबलेट और इंटरनेट का उपयोग करने के लिए मुफ्त डिजिटल साक्षरता प्रशिक्षण।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://digitalindia.gov.in',
                'eligibility' => '• Age 14-60 years\n• Non-IT literate citizens\n• BPL families preferred',
                'eligibility_hi' => '• आयु 14-60 वर्ष\n• गैर-आईटी साक्षर नागरिक\n• BPL परिवारों को प्राथमिकता',
                'benefits' => '• Free 10-day training\n• Computer basics\n• Internet browsing\n• Digital certificate',
                'benefits_hi' => '• मुफ्त 10 दिन का प्रशिक्षण\n• कंप्यूटर की बुनियादी बातें\n• इंटरनेट ब्राउज़िंग\n• डिजिटल प्रमाण पत्र',
                'application_process' => '1. Visit nearest Common Service Centre\n2. Register for training\n3. Complete 10-day course\n4. Appear for assessment\n5. Get digital literacy certificate',
                'application_process_hi' => '1. निकटतम कॉमन सर्विस सेंटर पर जाएं\n2. प्रशिक्षण के लिए पंजीकरण करें\n3. 10 दिन का कोर्स पूरा करें\n4. मूल्यांकन में भाग लें\n5. डिजिटल साक्षरता प्रमाण पत्र प्राप्त करें',
                'required_documents' => 'Aadhaar card, age proof, passport size photo',
                'required_documents_hi' => 'आधार कार्ड, आयु प्रमाण, पासपोर्ट साइज फोटो',
                'content' => '<h2>National Digital Literacy Mission</h2><p>NDLM aims to make at least one person per household digitally literate.</p>',
                'content_hi' => '<h2>राष्ट्रीय डिजिटल साक्षरता मिशन</h2><p>NDLM का उद्देश्य प्रत्येक परिवार में कम से कम एक व्यक्ति को डिजिटल रूप से साक्षर बनाना है।</p>',
                'meta_title' => 'Digital Literacy Mission - Free Computer Training | UmangIndia',
                'meta_title_hi' => 'डिजिटल साक्षरता मिशन - मुफ्त कंप्यूटर प्रशिक्षण | UmangIndia',
                'meta_description' => 'National Digital Literacy Mission - Free digital literacy training for citizens.',
                'meta_description_hi' => 'राष्ट्रीय डिजिटल साक्षरता मिशन - नागरिकों के लिए मुफ्त डिजिटल साक्षरता प्रशिक्षण।',
                'meta_keywords' => 'digital literacy, free computer training, NDLM',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Mid Day Meal Scheme',
                'title_hi' => 'मध्याह्न भोजन योजना',
                'slug' => 'mid-day-meal-scheme',
                'short_description' => 'Free cooked lunch for children in government schools (Classes 1-8).',
                'short_description_hi' => 'सरकारी विद्यालयों में बच्चों के लिए मुफ्त पका हुआ भोजन (कक्षा 1-8)।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://mdms.nic.in',
                'eligibility' => '• Children studying in Classes 1-8\n• Government and government-aided schools\n• Special Training centres',
                'eligibility_hi' => '• कक्षा 1-8 में पढ़ने वाले बच्चे\n• सरकारी और सहायता प्राप्त विद्यालय\n• विशेष प्रशिक्षण केंद्र',
                'benefits' => '• Free lunch for every child\n• Nutritional food\n• Calorie and protein norms met\n• Improved enrollment and attendance',
                'benefits_hi' => '• हर बच्चे के लिए मुफ्त भोजन\n• पौष्टिक भोजन\n• कैलोरी और प्रोटीन मानक पूरे\n• नामांकन और उपस्थिति में सुधार',
                'application_process' => '• Automatic for all enrolled students\n• No separate application needed',
                'application_process_hi' => '• सभी नामांकित छात्रों के लिए स्वचालित\n• अलग आवेदन की आवश्यकता नहीं',
                'required_documents' => 'School enrollment, student attendance register',
                'required_documents_hi' => 'विद्यालय नामांकन, छात्र उपस्थिति रजिस्टर',
                'content' => '<h2>Mid Day Meal Scheme</h2><p>PM POSHAN (formerly Mid Day Meal) provides nutritious cooked meals to children in government schools.</p>',
                'content_hi' => '<h2>मध्याह्न भोजन योजना</h2><p>पीएम पोषण (पहले मध्याह्न भोजन) सरकारी विद्यालयों में बच्चों को पौष्टिक पका हुआ भोजन प्रदान करता है।</p>',
                'meta_title' => 'Mid Day Meal - PM POSHAN Scheme | UmangIndia',
                'meta_title_hi' => 'मध्याह्न भोजन - पीएम पोषण योजना | UmangIndia',
                'meta_description' => 'PM POSHAN Mid Day Meal - Free nutritious lunch for school children.',
                'meta_description_hi' => 'पीएम पोषण मध्याह्न भोजन - स्कूली बच्चों के लिए मुफ्त पौष्टिक भोजन।',
                'meta_keywords' => 'mid day meal, PM POSHAN, school lunch, nutrition',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Rashtriya Madhyamik Shiksha Abhiyan',
                'title_hi' => 'राष्ट्रीय माध्यमिक शिक्षा अभियान',
                'slug' => 'rashtriya-madhyamik-shiksha-abhiyan',
                'short_description' => 'Improving quality and accessibility of secondary education across India.',
                'short_description_hi' => 'भारत भर में माध्यमिक शिक्षा की गुणवत्ता और पहुंच में सुधार।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://samagra.gov.in',
                'eligibility' => '• Government secondary and higher secondary schools\n• Students in Classes 9-12',
                'eligibility_hi' => '• सरकारी माध्यमिक और उच्च माध्यमिक विद्यालय\n• कक्षा 9-12 के छात्र',
                'benefits' => '• School infrastructure upgradation\n• Teacher training\n• Vocational education\n• Digital learning resources',
                'benefits_hi' => '• विद्यालय बुनियादी ढांचा उन्नयन\n• शिक्षक प्रशिक्षण\n• व्यावसायिक शिक्षा\n• डिजिटल शिक्षा संसाधन',
                'application_process' => '1. State government submits proposal\n2. Approval from MHRD\n3. Funds released to states',
                'application_process_hi' => '1. राज्य सरकार प्रस्ताव प्रस्तुत करती है\n2. MHRD से अनुमोदन\n3. राज्यों को धनराशि जारी',
                'required_documents' => 'School infrastructure report, enrollment data',
                'required_documents_hi' => 'विद्यालय बुनियादी ढांचा रिपोर्ट, नामांकन डेटा',
                'content' => '<h2>Rashtriya Madhyamik Shiksha Abhiyan</h2><p>RMSA aims to enhance access to secondary education and improve its quality.</p>',
                'content_hi' => '<h2>राष्ट्रीय माध्यमिक शिक्षा अभियान</h2><p>RMSA का उद्देश्य माध्यमिक शिक्षा तक पहुंच बढ़ाना और उसकी गुणवत्ता में सुधार करना है।</p>',
                'meta_title' => 'RMSA - Secondary Education Improvement | UmangIndia',
                'meta_title_hi' => 'RMSA - माध्यमिक शिक्षा सुधार | UmangIndia',
                'meta_description' => 'Rashtriya Madhyamik Shiksha Abhiyan for improving secondary education.',
                'meta_description_hi' => 'माध्यमिक शिक्षा में सुधार के लिए राष्ट्रीय माध्यमिक शिक्षा अभियान।',
                'meta_keywords' => 'RMSA, secondary education, school improvement',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Sarva Shiksha Abhiyan',
                'title_hi' => 'सर्व शिक्षा अभियान',
                'slug' => 'sarva-shiksha-abhiyan',
                'short_description' => 'Universal elementary education for children aged 6-14 years.',
                'short_description_hi' => '6-14 वर्ष की आयु के बच्चों के लिए सार्वभौमिक प्राथमिक शिक्षा।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://samagra.gov.in',
                'eligibility' => '• Children aged 6-14 years\n• All children irrespective of caste, creed, gender',
                'eligibility_hi' => '• 6-14 वर्ष आयु के बच्चे\n• जाति, धर्म, लिंग की परवाह किए बिना सभी बच्चे',
                'benefits' => '• Free and compulsory education\n• Textbooks and uniforms\n• Special training for out-of-school children\n• Girls education incentives',
                'benefits_hi' => '• मुफ्त और अनिवार्य शिक्षा\n• पाठ्य पुस्तकें और वर्दी\n• स्कूल से बाहर बच्चों के लिए विशेष प्रशिक्षण\n• बालिका शिक्षा प्रोत्साहन',
                'application_process' => '• Automatic enrollment in nearest government school\n• Contact Block Resource Centre',
                'application_process_hi' => '• निकटतम सरकारी विद्यालय में स्वचालित नामांकन\n• ब्लॉक संसाधन केंद्र से संपर्क',
                'required_documents' => 'Birth certificate, parent Aadhaar',
                'required_documents_hi' => 'जन्म प्रमाण पत्र, माता-पिता का आधार',
                'content' => '<h2>Sarva Shiksha Abhiyan</h2><p>SSA is a flagship programme for universalizing elementary education in India.</p>',
                'content_hi' => '<h2>सर्व शिक्षा अभियान</h2><p>SSA भारत में प्राथमिक शिक्षा को सार्वभौमिक बनाने की प्रमुख योजना है।</p>',
                'meta_title' => 'Sarva Shiksha Abhiyan - Free Elementary Education | UmangIndia',
                'meta_title_hi' => 'सर्व शिक्षा अभियान - मुफ्त प्राथमिक शिक्षा | UmangIndia',
                'meta_description' => 'Sarva Shiksha Abhiyan for universal elementary education.',
                'meta_description_hi' => 'सार्वभौमिक प्राथमिक शिक्षा के लिए सर्व शिक्षा अभियान।',
                'meta_keywords' => 'SSA, elementary education, free education, children',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Swami Vivekananda Merit cum Means Scholarship',
                'title_hi' => 'स्वामी विवेकानंद मेरिट कम मीन्स स्कॉलरशिप',
                'slug' => 'swami-vivekananda-merit-scholarship',
                'short_description' => 'Financial assistance for meritorious students from economically weaker sections.',
                'short_description_hi' => 'आर्थिक रूप से कमजोर वर्ग के मेधावी छात्रों के लिए वित्तीय सहायता।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://svmcm.wbhed.gov.in',
                'eligibility' => '• Students with 75%+ marks in last exam\n• Family income below ₹2.5 lakh/year\n• Domicile of West Bengal',
                'eligibility_hi' => '• पिछली परीक्षा में 75%+ अंक वाले छात्र\n• परिवार की आय ₹2.5 लाख/वर्ष से कम\n• पश्चिम बंगाल का निवासी',
                'benefits' => '• Up to ₹60,000 per year\n• Covers tuition and maintenance\n• For professional and technical courses',
                'benefits_hi' => '• ₹60,000 तक प्रति वर्ष\n• ट्यूशन और रखरखाव कवर\n• पेशेवर और तकनीकी पाठ्यक्रमों के लिए',
                'application_process' => '1. Apply online on SVMCM portal\n2. Upload marksheet and income certificate\n3. Verification by institution\n4. Scholarship credited to bank account',
                'application_process_hi' => '1. SVMCM पोर्टल पर ऑनलाइन आवेदन करें\n2. मार्कशीट और आय प्रमाण अपलोड करें\n3. संस्थान द्वारा सत्यापन\n4. बैंक खाते में छात्रवृत्ति जमा',
                'required_documents' => 'Marksheet, income certificate, Aadhaar, bank account',
                'required_documents_hi' => 'मार्कशीट, आय प्रमाण, आधार, बैंक खाता',
                'content' => '<h2>Swami Vivekananda Scholarship</h2><p>This scholarship provides financial assistance to meritorious students from economically weaker sections.</p>',
                'content_hi' => '<h2>स्वामी विवेकानंद छात्रवृत्ति</h2><p>यह छात्रवृत्ति आर्थिक रूप से कमजोर वर्ग के मेधावी छात्रों को वित्तीय सहायता प्रदान करती है।</p>',
                'meta_title' => 'Swami Vivekananda Scholarship - Merit Based | UmangIndia',
                'meta_title_hi' => 'स्वामी विवेकानंद छात्रवृत्ति - मेरिट आधारित | UmangIndia',
                'meta_description' => 'Swami Vivekananda Merit cum Means Scholarship for meritorious students.',
                'meta_description_hi' => 'मेधावी छात्रों के लिए स्वामी विवेकानंद मेरिट कम मीन्स स्कॉलरशिप।',
                'meta_keywords' => 'Vivekananda scholarship, merit scholarship, WB scholarship',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Indian Institute of Technology (IIT) Scholarships',
                'title_hi' => 'भारतीय प्रौद्योगिकी संस्थान (IIT) छात्रवृत्ति',
                'slug' => 'iit-scholarships',
                'short_description' => 'Fee waivers and scholarships for IIT students based on family income.',
                'short_description_hi' => 'परिवार की आय के आधार पर IIT छात्रों के लिए शुल्क माफी और छात्रवृत्ति।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://www.iit.ac.in',
                'eligibility' => '• Students admitted to IITs\n• Based on family income slabs',
                'eligibility_hi' => '• IIT में प्रवेशित छात्र\n• परिवार की आय स्लैब के आधार पर',
                'benefits' => '• 100% tuition waiver (income < ₹5 lakh)\n• 2/3 tuition waiver (₹5-10 lakh)\n• Partial waiver (₹10-15 lakh)\n• Full fee for > ₹15 lakh',
                'benefits_hi' => '• 100% ट्यूशन माफी (आय < ₹5 लाख)\n• 2/3 ट्यूशन माफी (₹5-10 लाख)\n• आंशिक माफी (₹10-15 लाख)\n• ₹15 लाख से अधिक पर पूर्ण शुल्क',
                'application_process' => '1. Apply through IIT admission process\n2. Submit income certificate\n3. Fee waiver automatically applied',
                'application_process_hi' => '1. IIT प्रवेश प्रक्रिया के माध्यम से आवेदन करें\n2. आय प्रमाण पत्र जमा करें\n3. शुल्क माफी स्वचालित रूप से लागू',
                'required_documents' => 'IIT admission letter, family income certificate, Aadhaar',
                'required_documents_hi' => 'IIT प्रवेश पत्र, परिवार आय प्रमाण पत्र, आधार',
                'content' => '<h2>IIT Scholarships</h2><p>IITs provide fee waivers and scholarships based on family income to ensure no student is denied education due to financial constraints.</p>',
                'content_hi' => '<h2>IIT छात्रवृत्ति</h2><p>IIT परिवार की आय के आधार पर शुल्क माफी और छात्रवृत्ति प्रदान करते हैं ताकि किसी भी छात्र को वित्तीय बाधाओं के कारण शिक्षा से वंचित न किया जाए।</p>',
                'meta_title' => 'IIT Scholarships - Fee Waiver for Students | UmangIndia',
                'meta_title_hi' => 'IIT छात्रवृत्ति - छात्रों के लिए शुल्क माफी | UmangIndia',
                'meta_description' => 'IIT Scholarships - Fee waivers based on family income.',
                'meta_description_hi' => 'IIT छात्रवृत्ति - परिवार की आय के आधार पर शुल्क माफी।',
                'meta_keywords' => 'IIT scholarship, fee waiver, IIT admission',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Pragati Scholarship for Girls',
                'title_hi' => 'बालिकाओं के लिए प्रगति छात्रवृत्ति',
                'slug' => 'pragati-scholarship-girls',
                'short_description' => 'AICTE scholarship for girls pursuing technical education (₹50,000/year).',
                'short_description_hi' => 'तकनीकी शिक्षा प्राप्त कर रही बालिकाओं के लिए AICTE छात्रवृत्ति (₹50,000/वर्ष)।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://www.aicte-india.org',
                'eligibility' => '• Girl students in AICTE approved institutions\n• Technical degree/diploma courses\n• Family income below ₹8 lakh',
                'eligibility_hi' => '• AICTE अनुमोदित संस्थानों में बालिका छात्र\n• तकनीकी डिग्री/डिप्लोमा पाठ्यक्रम\n• परिवार की आय ₹8 लाख से कम',
                'benefits' => '• ₹50,000 per year\n• For tuition and other expenses\n• Max 4 years',
                'benefits_hi' => '• ₹50,000 प्रति वर्ष\n• ट्यूशन और अन्य खर्चों के लिए\n• अधिकतम 4 वर्ष',
                'application_process' => '1. Apply on AICTE scholarship portal\n2. Upload required documents\n3. Institution verification\n4. Scholarship credited',
                'application_process_hi' => '1. AICTE छात्रवृत्ति पोर्टल पर आवेदन करें\n2. आवश्यक दस्तावेज अपलोड करें\n3. संस्थान सत्यापन\n4. छात्रवृत्ति जमा',
                'required_documents' => 'Marksheet, income certificate, admission letter, bank account',
                'required_documents_hi' => 'मार्कशीट, आय प्रमाण, प्रवेश पत्र, बैंक खाता',
                'content' => '<h2>Pragati Scholarship for Girls</h2><p>AICTE Pragati scheme encourages girls to pursue technical education by providing financial support.</p>',
                'content_hi' => '<h2>बालिकाओं के लिए प्रगति छात्रवृत्ति</h2><p>AICTE प्रगति योजना वित्तीय सहायता प्रदान करके बालिकाओं को तकनीकी शिक्षा प्राप्त करने के लिए प्रोत्साहित करती है।</p>',
                'meta_title' => 'Pragati Scholarship - Girls Technical Education | UmangIndia',
                'meta_title_hi' => 'प्रगति छात्रवृत्ति - बालिका तकनीकी शिक्षा | UmangIndia',
                'meta_description' => 'AICTE Pragati Scholarship for girls pursuing technical education.',
                'meta_description_hi' => 'तकनीकी शिक्षा प्राप्त कर रही बालिकाओं के लिए AICTE प्रगति छात्रवृत्ति।',
                'meta_keywords' => 'Pragati scholarship, girls education, AICTE scholarship',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Scholarship for Top Class Education for SC Students',
                'title_hi' => 'SC छात्रों के लिए शीर्ष श्रेणी शिक्षा छात्रवृत्ति',
                'slug' => 'top-class-education-sc',
                'short_description' => 'Full tuition and maintenance for SC students in premier institutions.',
                'short_description_hi' => 'प्रमुख संस्थानों में SC छात्रों के लिए पूर्ण शुल्क और रखरखाव।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://socialjustice.nic.in',
                'eligibility' => '• SC category students\n• Admitted in notified premier institutions\n• Family income below ₹8 lakh',
                'eligibility_hi' => '• SC श्रेणी के छात्र\n• अधिसूचित प्रमुख संस्थानों में प्रवेशित\n• परिवार की आय ₹8 लाख से कम',
                'benefits' => '• 100% tuition fees\n• Maintenance allowance\n• Books and stationery\n• Hostel charges',
                'benefits_hi' => '• 100% ट्यूशन फीस\n• रखरखाव भत्ता\n• किताबें और स्टेशनरी\n• छात्रावास शुल्क',
                'application_process' => '1. Apply through national scholarship portal\n2. Submit caste and income certificate\n3. Institution verification\n4. Direct benefit transfer',
                'application_process_hi' => '1. राष्ट्रीय छात्रवृत्ति पोर्टल के माध्यम से आवेदन करें\n2. जाति और आय प्रमाण जमा करें\n3. संस्थान सत्यापन\n4. प्रत्यक्ष लाभ हस्तांतरण',
                'required_documents' => 'Caste certificate, income certificate, admission letter, marksheet',
                'required_documents_hi' => 'जाति प्रमाण पत्र, आय प्रमाण पत्र, प्रवेश पत्र, मार्कशीट',
                'content' => '<h2>Top Class Education for SC Students</h2><p>This scheme provides full financial support to SC students admitted to premier institutions.</p>',
                'content_hi' => '<h2>SC छात्रों के लिए शीर्ष श्रेणी शिक्षा</h2><p>यह योजना प्रमुख संस्थानों में प्रवेशित SC छात्रों को पूर्ण वित्तीय सहायता प्रदान करती है।</p>',
                'meta_title' => 'Top Class Education SC Scholarship | UmangIndia',
                'meta_title_hi' => 'शीर्ष श्रेणी शिक्षा SC छात्रवृत्ति | UmangIndia',
                'meta_description' => 'Scholarship for SC students in premier institutions - full tuition and maintenance.',
                'meta_description_hi' => 'प्रमुख संस्थानों में SC छात्रों के लिए छात्रवृत्ति - पूर्ण शुल्क और रखरखाव।',
                'meta_keywords' => 'SC scholarship, top class education, dalit scholarship',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Post Matric Scholarship for SC Students',
                'title_hi' => 'SC छात्रों के लिए पोस्ट मैट्रिक छात्रवृत्ति',
                'slug' => 'post-matric-sc-scholarship',
                'short_description' => 'Financial assistance for SC students in post-matriculation studies.',
                'short_description_hi' => 'पोस्ट मैट्रिकलेशन अध्ययन में SC छात्रों के लिए वित्तीय सहायता।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://socialjustice.nic.in',
                'eligibility' => '• SC category students\n• Post-matric level studies\n• Family income below ₹2.5 lakh',
                'eligibility_hi' => '• SC श्रेणी के छात्र\n• पोस्ट मैट्रिक स्तर की पढ़ाई\n• परिवार की आय ₹2.5 लाख से कम',
                'benefits' => '• Tuition fees\n• Maintenance allowance\n• Study material allowance',
                'benefits_hi' => '• ट्यूशन फीस\n• रखरखाव भत्ता\n• अध्ययन सामग्री भत्ता',
                'application_process' => '1. Apply on NSP portal\n2. Submit required documents\n3. Institution and district verification',
                'application_process_hi' => '1. NSP पोर्टल पर आवेदन करें\n2. आवश्यक दस्तावेज जमा करें\n3. संस्थान और जिला सत्यापन',
                'required_documents' => 'Caste certificate, income certificate, marksheet, bank account',
                'required_documents_hi' => 'जाति प्रमाण, आय प्रमाण, मार्कशीट, बैंक खाता',
                'content' => '<h2>Post Matric Scholarship for SC</h2><p>This scheme supports SC students pursuing education beyond matriculation level.</p>',
                'content_hi' => '<h2>SC छात्रों के लिए पोस्ट मैट्रिक छात्रवृत्ति</h2><p>यह योजना मैट्रिकलेशन से आगे की पढ़ाई कर रहे SC छात्रों का समर्थन करती है।</p>',
                'meta_title' => 'Post Matric SC Scholarship | UmangIndia',
                'meta_title_hi' => 'पोस्ट मैट्रिक SC छात्रवृत्ति | UmangIndia',
                'meta_description' => 'Post Matric Scholarship for SC students in higher education.',
                'meta_description_hi' => 'उच्च शिक्षा में SC छात्रों के लिए पोस्ट मैट्रिक छात्रवृत्ति।',
                'meta_keywords' => 'post matric scholarship, SC students, higher education',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Pre Matric Scholarship for SC Students',
                'title_hi' => 'SC छात्रों के लिए प्री-मैट्रिक छात्रवृत्ति',
                'slug' => 'pre-matric-sc-scholarship',
                'short_description' => 'Financial support for SC students in classes 9-10.',
                'short_description_hi' => 'कक्षा 9-10 में SC छात्रों के लिए वित्तीय सहायता।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://socialjustice.nic.in',
                'eligibility' => '• SC students in classes 9-10\n• Family income below ₹2 lakh',
                'eligibility_hi' => '• कक्षा 9-10 में SC छात्र\n• परिवार की आय ₹2 लाख से कम',
                'benefits' => '• ₹150-350 per month\n• Tuition fee support\n• Book and stationery allowance',
                'benefits_hi' => '• ₹150-350 प्रति माह\n• ट्यूशन फीस सहायता\n• किताब और स्टेशनरी भत्ता',
                'application_process' => '1. Apply through school\n2. Submit caste and income certificate\n3. State-level verification',
                'application_process_hi' => '1. विद्यालय के माध्यम से आवेदन करें\n2. जाति और आय प्रमाण जमा करें\n3. राज्य स्तरीय सत्यापन',
                'required_documents' => 'Caste certificate, income certificate, school enrollment',
                'required_documents_hi' => 'जाति प्रमाण, आय प्रमाण, विद्यालय नामांकन',
                'content' => '<h2>Pre Matric Scholarship for SC</h2><p>Financial support for SC students studying in classes 9 and 10 to reduce dropout rates.</p>',
                'content_hi' => '<h2>SC छात्रों के लिए प्री-मैट्रिक छात्रवृत्ति</h2><p>ड्रॉपआउट दर कम करने के लिए कक्षा 9 और 10 में पढ़ने वाले SC छात्रों के लिए वित्तीय सहायता।</p>',
                'meta_title' => 'Pre Matric SC Scholarship | UmangIndia',
                'meta_title_hi' => 'प्री-मैट्रिक SC छात्रवृत्ति | UmangIndia',
                'meta_description' => 'Pre Matric Scholarship for SC students in classes 9-10.',
                'meta_description_hi' => 'कक्षा 9-10 में SC छात्रों के लिए प्री-मैट्रिक छात्रवृत्ति।',
                'meta_keywords' => 'pre matric scholarship, SC students, class 9 10',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Central Sector Scheme of Scholarship',
                'title_hi' => 'केंद्रीय क्षेत्र छात्रवृत्ति योजना',
                'slug' => 'central-sector-scholarship',
                'short_description' => 'Merit-based scholarship for top 20% students in boards and entrance exams.',
                'short_description_hi' => 'बोर्ड और प्रवेश परीक्षाओं में शीर्ष 20% छात्रों के लिए मेरिट आधारित छात्रवृत्ति।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://www.scholarships.gov.in',
                'eligibility' => '• Top 20% in class 12 board exams\n• Family income below ₹8 lakh\n• Regular degree course students',
                'eligibility_hi' => '• कक्षा 12 बोर्ड परीक्षा में शीर्ष 20%\n• परिवार की आय ₹8 लाख से कम\n• नियमित डिग्री पाठ्यक्रम के छात्र',
                'benefits' => '• ₹10,000-₹20,000 per year\n• For graduation, post-graduation, and professional courses\n• Up to 5 years',
                'benefits_hi' => '• ₹10,000-₹20,000 प्रति वर्ष\n• स्नातक, स्नातकोत्तर और पेशेवर पाठ्यक्रमों के लिए\n• 5 वर्ष तक',
                'application_process' => '1. Apply on NSP portal\n2. Submit class 12 marksheet\n3. Income certificate\n4. Bank account details',
                'application_process_hi' => '1. NSP पोर्टल पर आवेदन करें\n2. कक्षा 12 की मार्कशीट जमा करें\n3. आय प्रमाण पत्र\n4. बैंक खाता विवरण',
                'required_documents' => 'Class 12 marksheet, income certificate, Aadhaar, bank account',
                'required_documents_hi' => 'कक्षा 12 मार्कशीट, आय प्रमाण, आधार, बैंक खाता',
                'content' => '<h2>Central Sector Scholarship</h2><p>This scholarship is awarded to top 20% students based on merit in class 12 board exams and entrance examinations.</p>',
                'content_hi' => '<h2>केंद्रीय क्षेत्र छात्रवृत्ति</h2><p>यह छात्रवृत्ति कक्षा 12 बोर्ड परीक्षा और प्रवेश परीक्षाओं में मेरिट के आधार पर शीर्ष 20% छात्रों को दी जाती है।</p>',
                'meta_title' => 'Central Sector Scholarship - Merit Based | UmangIndia',
                'meta_title_hi' => 'केंद्रीय क्षेत्र छात्रवृत्ति - मेरिट आधारित | UmangIndia',
                'meta_description' => 'Central Sector Scholarship for top 20% students in board exams.',
                'meta_description_hi' => 'बोर्ड परीक्षाओं में शीर्ष 20% छात्रों के लिए केंद्रीय क्षेत्र छात्रवृत्ति।',
                'meta_keywords' => 'central sector scholarship, merit scholarship, board toppers',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'ISRO Young Scientist Program',
                'title_hi' => 'ISRO यंग साइंटिस्ट प्रोग्राम',
                'slug' => 'isro-young-scientist-program',
                'short_description' => 'Annual space workshop for school students by ISRO.',
                'short_description_hi' => 'ISRO द्वारा स्कूली छात्रों के लिए वार्षिक अंतरिक्ष कार्यशाला।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://www.isro.gov.in',
                'eligibility' => '• Class 9 students\n• Age 14-18 years\n• Studying in India',
                'eligibility_hi' => '• कक्षा 9 के छात्र\n• आयु 14-18 वर्ष\n• भारत में पढ़ रहे',
                'benefits' => '• Visit ISRO facilities\n• Interact with scientists\n• Hands-on space activities\n• Certificate of participation',
                'benefits_hi' => '• ISRO सुविधाओं का भ्रमण\n• वैज्ञानिकों से बातचीत\n• व्यावहारिक अंतरिक्ष गतिविधियां\n• भागीदारी प्रमाण पत्र',
                'application_process' => '1. Apply through school\n2. Selection by ISRO\n3. Attend 2-week summer program',
                'application_process_hi' => '1. विद्यालय के माध्यम से आवेदन करें\n2. ISRO द्वारा चयन\n3. 2 सप्ताह का ग्रीष्मकालीन कार्यक्रम में भाग लें',
                'required_documents' => 'School identity card, class 9 marksheet, parental consent',
                'required_documents_hi' => 'विद्यालय पहचान पत्र, कक्षा 9 की मार्कशीट, अभिभावक सहमति',
                'content' => '<h2>ISRO Young Scientist Program</h2><p>YSIP is a two-week residential program for school students to learn about space science and technology at ISRO centers.</p>',
                'content_hi' => '<h2>ISRO यंग साइंटिस्ट प्रोग्राम</h2><p>YSIP एक दो सप्ताह का आवासीय कार्यक्रम है जो स्कूली छात्रों को ISRO केंद्रों में अंतरिक्ष विज्ञान और प्रौद्योगिकी के बारे में सीखने का अवसर देता है।</p>',
                'meta_title' => 'ISRO Young Scientist Program | UmangIndia',
                'meta_title_hi' => 'ISRO यंग साइंटिस्ट प्रोग्राम | UmangIndia',
                'meta_description' => 'ISRO Young Scientist Program - space workshop for school students.',
                'meta_description_hi' => 'ISRO यंग साइंटिस्ट प्रोग्राम - स्कूली छात्रों के लिए अंतरिक्ष कार्यशाला।',
                'meta_keywords' => 'ISRO, young scientist, space program, students',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'DRDO Entry Scheme for Engineers',
                'title_hi' => 'इंजीनियरों के लिए DRDO प्रवेश योजना',
                'slug' => 'drdo-entry-scheme',
                'short_description' => 'Career opportunities in DRDO through GATE and direct recruitment.',
                'short_description_hi' => 'GATE और सीधी भर्ती के माध्यम से DRDO में करियर के अवसर।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://www.drdo.gov.in',
                'eligibility' => '• Engineering graduates with GATE score\n• Age below 28 years\n• Indian citizenship',
                'eligibility_hi' => '• GATE स्कोर के साथ इंजीनियरिंग स्नातक\n• आयु 28 वर्ष से कम\n• भारतीय नागरिकता',
                'benefits' => '• Government job at DRDO\n• Research opportunities\n• Competitive salary\n• Defense benefits',
                'benefits_hi' => '• DRDO में सरकारी नौकरी\n• शोध अवसर\n• प्रतिस्पर्धी वेतन\n• रक्षा लाभ',
                'application_process' => '1. Clear GATE exam\n2. Apply through RAC website\n3. Appear for interview\n4. Medical examination',
                'application_process_hi' => '1. GATE परीक्षा उत्तीर्ण करें\n2. RAC वेबसाइट के माध्यम से आवेदन करें\n3. साक्षात्कार में भाग लें\n4. चिकित्सा परीक्षा',
                'required_documents' => 'GATE scorecard, engineering degree, Aadhaar, photograph',
                'required_documents_hi' => 'GATE स्कोरकार्ड, इंजीनियरिंग डिग्री, आधार, फोटो',
                'content' => '<h2>DRDO Entry Scheme</h2><p>DRDO recruits scientists and engineers through GATE-based selection and direct recruitment drives.</p>',
                'content_hi' => '<h2>DRDO प्रवेश योजना</h2><p>DRDO GATE-आधारित चयन और सीधी भर्ती ड्राइव के माध्यम से वैज्ञानिकों और इंजीनियरों की भर्ती करता है।</p>',
                'meta_title' => 'DRDO Entry Scheme - Defense Research Career | UmangIndia',
                'meta_title_hi' => 'DRDO प्रवेश योजना - रक्षा शोध करियर | UmangIndia',
                'meta_description' => 'DRDO Entry Scheme for engineers through GATE and direct recruitment.',
                'meta_description_hi' => 'GATE और सीधी भर्ती के माध्यम से इंजीनियरों के लिए DRDO प्रवेश योजना।',
                'meta_keywords' => 'DRDO, defense research, GATE, scientist recruitment',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Indian Army Agneepath Scheme',
                'title_hi' => 'भारतीय सेना अग्निपथ योजना',
                'slug' => 'agneepath-scheme',
                'short_description' => 'Short-term military service for youth aged 17.5-21 with retirement benefits.',
                'short_description_hi' => '17.5-21 वर्ष के युवाओं के लिए अल्पकालिक सैन्य सेवा और सेवानिवृत्ति लाभ।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://joinindianarmy.nic.in',
                'eligibility' => '• Age 17.5-21 years\n• Male and female candidates\n• Class 10 or 12 pass\n• Medically and physically fit',
                'eligibility_hi' => '• आयु 17.5-21 वर्ष\n• पुरुष और महिला उम्मीदवार\n• कक्षा 10 या 12 पास\n• चिकित्सकीय और शारीरिक रूप से फिट',
                'benefits' => '• 4-year military service\n• ₹30,000-₹40,000 monthly salary\n• ₹11.71 lakh lump sum after 4 years\n• 10% reservation in police/CAPF\n• Priority in bank jobs',
                'benefits_hi' => '• 4 वर्ष की सैन्य सेवा\n• ₹30,000-₹40,000 मासिक वेतन\n• 4 वर्ष बाद ₹11.71 लाख एकमुश्त\n• पुलिस/CAPF में 10% आरक्षण\n• बैंक नौकरियों में प्राथमिकता',
                'application_process' => '1. Register on joinindianarmy.nic.in\n2. Appear for written exam\n3. Physical fitness test\n4. Medical examination\n5. Training at military center',
                'application_process_hi' => '1. joinindianarmy.nic.in पर पंजीकरण करें\n2. लिखित परीक्षा में भाग लें\n3. शारीरिक फिटनेस टेस्ट\n4. चिकित्सा परीक्षा\n5. सैन्य केंद्र में प्रशिक्षण',
                'required_documents' => 'Class 10/12 certificate, Aadhaar, birth certificate, fitness certificate',
                'required_documents_hi' => 'कक्षा 10/12 प्रमाण पत्र, आधार, जन्म प्रमाण, फिटनेस प्रमाण',
                'content' => '<h2>Agneepath Scheme</h2><p>Agneepath is a tour of duty scheme for recruitment of soldiers in the Indian Army for 4 years.</p>',
                'content_hi' => '<h2>अग्निपथ योजना</h2><p>अग्निपथ भारतीय सेना में 4 वर्ष के लिए सैनिकों की भर्ती के लिए टूर ऑफ ड्यूटी योजना है।</p>',
                'meta_title' => 'Agneepath Scheme - Indian Army Recruitment | UmangIndia',
                'meta_title_hi' => 'अग्निपथ योजना - भारतीय सेना भर्ती | UmangIndia',
                'meta_description' => 'Agneepath Scheme - 4-year military service with ₹11.71 lakh retirement benefits.',
                'meta_description_hi' => 'अग्निपथ योजना - ₹11.71 लाख सेवानिवृत्ति लाभ के साथ 4 वर्ष की सैन्य सेवा।',
                'meta_keywords' => 'Agneepath, Indian Army, military recruitment, army',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Indian Navy Agniveer Scheme',
                'title_hi' => 'भारतीय नौसेना अग्निवीर योजना',
                'slug' => 'agniveer-navy-scheme',
                'short_description' => '4-year naval service with competitive salary and post-service benefits.',
                'short_description_hi' => 'प्रतिस्पर्धी वेतन और सेवा-पश्चात लाभों के साथ 4 वर्ष की नौसैनिक सेवा।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://www.joinindiannavy.gov.in',
                'eligibility' => '• Age 17.5-21 years\n• Class 10 or 12 with physics, maths\n• Medically fit',
                'eligibility_hi' => '• आयु 17.5-21 वर्ष\n• भौतिकी, गणित के साथ कक्षा 10 या 12\n• चिकित्सकीय रूप से फिट',
                'benefits' => '• ₹30,000-₹40,000 monthly\n• ₹11.71 lakh after 4 years\n• Post-service career opportunities\n• Skill development training',
                'benefits_hi' => '• ₹30,000-₹40,000 मासिक\n• 4 वर्ष बाद ₹11.71 लाख\n• सेवा-पश्चात करियर अवसर\n• कौशल विकास प्रशिक्षण',
                'application_process' => '1. Apply on joinindiannavy.gov.in\n2. Written examination\n3. Physical fitness test\n4. Medical examination\n5. Training at naval establishments',
                'application_process_hi' => '1. joinindiannavy.gov.in पर आवेदन करें\n2. लिखित परीक्षा\n3. शारीरिक फिटनेस टेस्ट\n4. चिकित्सा परीक्षा\n5. नौसेना प्रतिष्ठानों में प्रशिक्षण',
                'required_documents' => 'Class 10/12 certificate, Aadhaar, birth certificate, fitness certificate',
                'required_documents_hi' => 'कक्षा 10/12 प्रमाण पत्र, आधार, जन्म प्रमाण, फिटनेस प्रमाण',
                'content' => '<h2>Indian Navy Agniveer</h2><p>The Agniveer scheme provides an opportunity to serve in the Indian Navy for 4 years with competitive compensation.</p>',
                'content_hi' => '<h2>भारतीय नौसेना अग्निवीर</h2><p>अग्निवीर योजना प्रतिस्पर्धी मुआवजे के साथ 4 वर्ष के लिए भारतीय नौसेना में सेवा करने का अवसर प्रदान करती है।</p>',
                'meta_title' => 'Indian Navy Agniveer - Naval Service | UmangIndia',
                'meta_title_hi' => 'भारतीय नौसेना अग्निवीर - नौसैनिक सेवा | UmangIndia',
                'meta_description' => 'Indian Navy Agniveer Scheme - 4-year naval service with benefits.',
                'meta_description_hi' => 'भारतीय नौसेना अग्निवीर योजना - लाभों के साथ 4 वर्ष की नौसैनिक सेवा।',
                'meta_keywords' => 'Agniveer, Indian Navy, naval recruitment, navy',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Indian Air Force Agniveer Vayu',
                'title_hi' => 'भारतीय वायु सेना अग्निवीर वायु',
                'slug' => 'agniveer-vayu-scheme',
                'short_description' => '4-year air force service with technical and non-technical trades.',
                'short_description_hi' => 'तकनीकी और गैर-तकनीकी व्यवसायों के साथ 4 वर्ष की वायु सेवा सेवा।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://afcat.cdac.in',
                'eligibility' => '• Age 17.5-21 years\n• Class 12 with Physics and Maths\n• Or 3-year diploma holders',
                'eligibility_hi' => '• आयु 17.5-21 वर्ष\n• भौतिकी और गणित के साथ कक्षा 12\n• या 3 वर्षीय डिप्लोमा धारक',
                'benefits' => '• ₹30,000-₹40,000 monthly\n• ₹11.71 lakh after 4 years\n• Technical skill training\n• Air force experience',
                'benefits_hi' => '• ₹30,000-₹40,000 मासिक\n• 4 वर्ष बाद ₹11.71 लाख\n• तकनीकी कौशल प्रशिक्षण\n• वायु सेवा का अनुभव',
                'application_process' => '1. Apply on afcat.cdac.in\n2. Online examination\n3. AFSB interview\n4. Medical examination\n5. Training at air force stations',
                'application_process_hi' => '1. afcat.cdac.in पर आवेदन करें\n2. ऑनलाइन परीक्षा\n3. AFSB साक्षात्कार\n4. चिकित्सा परीक्षा\n5. वायु सेवा स्टेशनों पर प्रशिक्षण',
                'required_documents' => 'Class 12 certificate, Aadhaar, birth certificate, fitness certificate',
                'required_documents_hi' => 'कक्षा 12 प्रमाण पत्र, आधार, जन्म प्रमाण, फिटनेस प्रमाण',
                'content' => '<h2>Indian Air Force Agniveer Vayu</h2><p>Agniveer Vayu recruits youth for 4-year service in the Indian Air Force across various trades.</p>',
                'content_hi' => '<h2>भारतीय वायु सेना अग्निवीर वायु</h2><p>अग्निवीर वायु विभिन्न व्यवसायों में भारतीय वायु सेना में 4 वर्ष की सेवा के लिए युवाओं की भर्ती करता है।</p>',
                'meta_title' => 'IAF Agniveer Vayu - Air Force Recruitment | UmangIndia',
                'meta_title_hi' => 'IAF अग्निवीर वायु - वायु सेना भर्ती | UmangIndia',
                'meta_description' => 'Indian Air Force Agniveer Vayu - 4-year air force service.',
                'meta_description_hi' => 'भारतीय वायु सेना अग्निवीर वायु - 4 वर्ष की वायु सेना सेवा।',
                'meta_keywords' => 'Agniveer Vayu, Indian Air Force, air force recruitment',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'SSC Recruitment Exams',
                'title_hi' => 'SSC भर्ती परीक्षाएं',
                'slug' => 'ssc-recruitment',
                'short_description' => 'Staff Selection Commission exams for central government jobs.',
                'short_description_hi' => 'केंद्रीय सरकारी नौकरियों के लिए कर्मचारी चयन आयोग परीक्षाएं।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://ssc.nic.in',
                'eligibility' => '• Age 18-32 years (varies by post)\n• Graduation from recognized university\n• Indian citizenship',
                'eligibility_hi' => '• आयु 18-32 वर्ष (पद के अनुसार भिन्न)\n• मान्यता प्राप्त विश्वविद्यालय से स्नातक\n• भारतीय नागरिकता',
                'benefits' => '• Central government jobs\n• Group B and C positions\n• Competitive salary\n• Pension and benefits',
                'benefits_hi' => '• केंद्रीय सरकारी नौकरियां\n• ग्रुप B और C पद\n• प्रतिस्पर्धी वेतन\n• पेंशन और लाभ',
                'application_process' => '1. Register on ssc.nic.in\n2. Apply for specific exam\n3. Appear for CGL/CHSL/MTS exam\n4. Skill test/interview\n5. Document verification',
                'application_process_hi' => '1. ssc.nic.in पर पंजीकरण करें\n2. विशिष्ट परीक्षा के लिए आवेदन करें\n3. CGL/CHSL/MTS परीक्षा में भाग लें\n4. कौशल परीक्षा/साक्षात्कार\n5. दस्तावेज सत्यापन',
                'required_documents' => 'Graduation degree, Aadhaar, age proof, category certificate',
                'required_documents_hi' => 'स्नातक डिग्री, आधार, आयु प्रमाण, श्रेणी प्रमाण',
                'content' => '<h2>SSC Recruitment</h2><p>Staff Selection Commission conducts various exams for recruitment to central government posts.</p>',
                'content_hi' => '<h2>SSC भर्ती</h2><p>कर्मचारी चयन आयोग केंद्रीय सरकारी पदों पर भर्ती के लिए विभिन्न परीक्षाएं आयोजित करता है।</p>',
                'meta_title' => 'SSC Recruitment - Government Jobs | UmangIndia',
                'meta_title_hi' => 'SSC भर्ती - सरकारी नौकरियां | UmangIndia',
                'meta_description' => 'SSC Recruitment Exams - CGL, CHSL, MTS for central government jobs.',
                'meta_description_hi' => 'SSC भर्ती परीक्षाएं - केंद्रीय सरकारी नौकरियों के लिए CGL, CHSL, MTS।',
                'meta_keywords' => 'SSC, government jobs, CGL, CHSL, recruitment',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'UPSC Civil Services Examination',
                'title_hi' => 'UPSC सिविल सेवा परीक्षा',
                'slug' => 'upsc-civil-services',
                'short_description' => "India's premier exam for IAS, IPS, IFS and other Group A services.",
                'short_description_hi' => 'IAS, IPS, IFS और अन्य ग्रुप A सेवाओं के लिए भारत की प्रमुख परीक्षा।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://upsc.gov.in',
                'eligibility' => '• Age 21-32 years\n• Graduation from any discipline\n• Indian citizenship\n• 6 attempts (General)',
                'eligibility_hi' => '• आयु 21-32 वर्ष\n• किसी भी विषय से स्नातक\n• भारतीय नागरिकता\n• 6 प्रयास (सामान्य)',
                'benefits' => '• IAS, IPS, IFS cadre\n• Prestigious government career\n• Policy making roles\n• All India service',
                'benefits_hi' => '• IAS, IPS, IFS कैडर\n• प्रतिष्ठित सरकारी करियर\n• नीति निर्माण भूमिकाएं\n• अखिल भारतीय सेवा',
                'application_process' => '1. Apply on upsc.gov.in\n2. Preliminary exam\n3. Main examination\n4. Personality test (Interview)\n5. Final merit list',
                'application_process_hi' => '1. upsc.gov.in पर आवेदन करें\n2. प्रारंभिक परीक्षा\n3. मुख्य परीक्षा\n4. व्यक्तित्व परीक्षण (साक्षात्कार)\n5. अंतिम मेरिट सूची',
                'required_documents' => 'Graduation degree, age proof, category certificate, photo ID',
                'required_documents_hi' => 'स्नातक डिग्री, आयु प्रमाण, श्रेणी प्रमाण, फोटो पहचान',
                "content" => "<h2>UPSC Civil Services</h2><p>The Civil Services Examination conducted by UPSC is the gateway to India's most prestigious government positions.</p>",
                'content_hi' => '<h2>UPSC सिविल सेवा</h2><p>UPSC द्वारा आयोजित सिविल सेवा परीक्षा भारत के सबसे प्रतिष्ठित सरकारी पदों का प्रवेश द्वार है।</p>',
                'meta_title' => 'UPSC Civil Services - IAS IPS IFS | UmangIndia',
                'meta_title_hi' => 'UPSC सिविल सेवा - IAS IPS IFS | UmangIndia',
                'meta_description' => 'UPSC Civil Services Examination for IAS, IPS, IFS positions.',
                'meta_description_hi' => 'IAS, IPS, IFS पदों के लिए UPSC सिविल सेवा परीक्षा।',
                'meta_keywords' => 'UPSC, civil services, IAS, IPS, government exam',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'IBPS Bank Recruitment',
                'title_hi' => 'IBPS बैंक भर्ती',
                'slug' => 'ibps-bank-recruitment',
                'short_description' => 'Recruitment exams for clerks, POs and specialist officers in public sector banks.',
                'short_description_hi' => 'सार्वजनिक क्षेत्र के बैंकों में क्लर्क, PO और विशेषज्ञ अधिकारियों के लिए भर्ती परीक्षाएं।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://www.ibps.in',
                'eligibility' => '• Age 20-30 years\n• Graduation from recognized university\n• Computer literacy',
                'eligibility_hi' => '• आयु 20-30 वर्ष\n• मान्यता प्राप्त विश्वविद्यालय से स्नातक\n• कंप्यूटर साक्षरता',
                'benefits' => '• Public sector bank jobs\n• Clerical and officer cadre\n• Pension and medical benefits\n• Job security',
                'benefits_hi' => '• सार्वजनिक क्षेत्र बैंक नौकरियां\n• क्लर्क और अधिकारी कैडर\n• पेंशन और चिकित्सा लाभ\n• नौकरी सुरक्षा',
                'application_process' => '1. Register on ibps.in\n2. Apply for PO/Clerk/SO exam\n3. Preliminary exam\n4. Main exam\n5. Interview and document verification',
                'application_process_hi' => '1. ibps.in पर पंजीकरण करें\n2. PO/Clerk/SO परीक्षा के लिए आवेदन करें\n3. प्रारंभिक परीक्षा\n4. मुख्य परीक्षा\n5. साक्षात्कार और दस्तावेज सत्यापन',
                'required_documents' => 'Graduation degree, Aadhaar, photo, signature scan',
                'required_documents_hi' => 'स्नातक डिग्री, आधार, फोटो, हस्ताक्षर स्कैन',
                'content' => '<h2>IBPS Bank Recruitment</h2><p>IBPS conducts recruitment examinations for various positions in public sector banks across India.</p>',
                'content_hi' => '<h2>IBPS बैंक भर्ती</h2><p>IBPS भारत भर में सार्वजनिक क्षेत्र के बैंकों में विभिन्न पदों के लिए भर्ती परीक्षाएं आयोजित करता है।</p>',
                'meta_title' => 'IBPS Bank Recruitment - Clerk PO SO | UmangIndia',
                'meta_title_hi' => 'IBPS बैंक भर्ती - Clerk PO SO | UmangIndia',
                'meta_description' => 'IBPS Bank Recruitment for Clerk, PO and Specialist Officers.',
                'meta_description_hi' => 'Clerk, PO और विशेषज्ञ अधिकारियों के लिए IBPS बैंक भर्ती।',
                'meta_keywords' => 'IBPS, bank recruitment, PO, clerk, banking jobs',
                'application_deadline' => null,
            ],
            [
                'category_slug' => 'education',
                'title' => 'Railway Recruitment Board (RRB) Exams',
                'title_hi' => 'रेलवे भर्ती बोर्ड (RRB) परीक्षाएं',
                'slug' => 'rrb-recruitment',
                'short_description' => 'Recruitment for various positions in Indian Railways - ALP, Technician, Group D.',
                'short_description_hi' => 'भारतीय रेलवे में विभिन्न पदों के लिए भर्ती - ALP, तकनीशियन, ग्रुप D।',
                'status' => 'active',
                'is_featured' => false,
                'official_website' => 'https://indianrailways.gov.in',
                'eligibility' => '• Age 18-33 years\n• ITI/Diploma/Degree depending on post\n• Indian citizenship',
                'eligibility_hi' => '• आयु 18-33 वर्ष\n• पद के अनुसार ITI/डिप्लोमा/डिग्री\n• भारतीय नागरिकता',
                'benefits' => '• Government job in railways\n• Railway travel pass\n• Medical facilities\n• Pension and housing',
                'benefits_hi' => '• रेलवे में सरकारी नौकरी\n• रेलवे यात्रा पास\n• चिकित्सा सुविधाएं\n• पेंशन और आवास',
                'application_process' => '1. Apply on rrb regional website\n2. CBT 1 exam\n3. CBT 2/Physical test\n4. Document verification\n5. Medical examination',
                'application_process_hi' => '1. RRB क्षेत्रीय वेबसाइट पर आवेदन करें\n2. CBT 1 परीक्षा\n3. CBT 2/शारीरिक परीक्षा\n4. दस्तावेज सत्यापन\n5. चिकित्सा परीक्षा',
                'required_documents' => 'Educational certificates, Aadhaar, age proof, category certificate',
                'required_documents_hi' => 'शैक्षणिक प्रमाण पत्र, आधार, आयु प्रमाण, श्रेणी प्रमाण',
                'content' => '<h2>Railway Recruitment Board</h2><p>RRB conducts exams for recruitment to various technical and non-technical posts in Indian Railways.</p>',
                'content_hi' => '<h2>रेलवे भर्ती बोर्ड</h2><p>RRB भारतीय रेलवे में विभिन्न तकनीकी और गैर-तकनीकी पदों पर भर्ती के लिए परीक्षाएं आयोजित करता है।</p>',
                'meta_title' => 'RRB Recruitment - Railway Jobs | UmangIndia',
                'meta_title_hi' => 'RRB भर्ती - रेलवे नौकरियां | UmangIndia',
                'meta_description' => 'RRB Recruitment for ALP, Technician, Group D in Indian Railways.',
                'meta_description_hi' => 'भारतीय रेलवे में ALP, तकनीशियन, ग्रुप D के लिए RRB भर्ती।',
                'meta_keywords' => 'RRB, railway recruitment, ALP, group D, railway jobs',
                'application_deadline' => null,
            ],
        ];

        foreach ($schemes as $scheme) {
            $categoryId = $categories[$scheme['category_slug']] ?? null;
            if (!$categoryId) continue;

            unset($scheme['category_slug']);

            Scheme::updateOrCreate(
                ['slug' => $scheme['slug']],
                array_merge($scheme, [
                    'category_id' => $categoryId,
                    'state_id' => 1,
                    'meta_keywords' => $scheme['meta_keywords'] ?? '',
                    'meta_title' => $scheme['meta_title'] ?? $scheme['title'],
                    'meta_description' => $scheme['meta_description'] ?? $scheme['short_description'],
                    'meta_title_hi' => $scheme['meta_title_hi'] ?? $scheme['title_hi'],
                    'meta_description_hi' => $scheme['meta_description_hi'] ?? $scheme['short_description_hi'],
                ])
            );
        }

        $this->command->info('Expanded scheme seeder: ' . count($schemes) . ' schemes processed.');
    }
}
