-- Expand thin content fields for top schemes (AdSense low-value content fix)
-- Target: fields under 150 chars that need scheme-specific depth

-- #15 PM Garib Kalyan Anna Yojana (views=171) — rd=25, be=82, el=118 — CRITICAL
UPDATE schemes SET required_documents = 'Beneficiaries need to provide the following documents to receive food grains under PM Garib Kalyan Anna Yojana: (1) Ration Card or any government-issued family identification document linked to the Public Distribution System (PDS), (2) Aadhaar Card of the head of the family for identity verification, (3) Bank account details if cash transfers are applicable in their state, and (4) Mobile number registered with the ration shop or PDS dealer. Family members listed on the Below Poverty Line (BPL) ration card are automatically eligible and do not need to submit separate applications.' WHERE id=15 AND LENGTH(IFNULL(required_documents,''))<150;
UPDATE schemes SET benefits = 'Each eligible family receives 5 kg of food grains (wheat or rice) per person per month absolutely free of cost under PM Garib Kalyan Anna Yojana. In addition to grains, 1 kg of chana (gram) per family per month was also provided when the scheme was active. The scheme was initially launched during the COVID-19 pandemic to provide nutritional support to below-poverty-line families and was extended multiple times by the Government of India. This benefit is over and above the regular quota received under the National Food Security Act (NFSA) ration distribution.' WHERE id=15 AND LENGTH(IFNULL(benefits,''))<150;
UPDATE schemes SET eligibility = 'All families holding a valid Below Poverty Line (BPL) ration card issued under the National Food Security Act (NFSA) are eligible for PM Garib Kalyan Anna Yojana. Antyodaya Anna Yojana (AAY) households — the poorest of the poor — are also covered under this scheme. Priority Households (PHH) identified by the state governments as per NFSA guidelines are eligible as well. The scheme does not require separate registration; families already listed in the PDS database receive the benefits automatically.' WHERE id=15 AND LENGTH(IFNULL(eligibility,''))<150;
UPDATE schemes SET application_process = 'No separate application is required for PM Garib Kalyan Anna Yojana. Eligible beneficiaries already enrolled under the National Food Security Act (NFSA) with a valid ration card receive the additional food grains automatically at their designated Fair Price Shop (ration shop). Visit your local ration shop during the distribution period with your ration card and Aadhaar card. If you are not receiving the grains despite being a ration card holder, contact your local Food and Civil Supplies office or the ration shop dealer to resolve the issue.' WHERE id=15 AND LENGTH(IFNULL(application_process,''))<150;

-- #109 Sanjivani Health Scheme MP (views=195) — rd=79
UPDATE schemes SET required_documents = 'Applicants for Sanjivani Mukhyamantri Health Scheme in Madhya Pradesh need the following documents: (1) Aadhaar Card of all family members for identity verification, (2) BPL ration card or income certificate issued by a competent authority, (3) Domicile certificate of Madhya Pradesh residency, (4) Recent passport-size photographs of the head of family, (5) Bank account passbook with IFSC code for any cash benefits, and (6) Mobile number for scheme notifications. For senior citizen applicants, age proof such as birth certificate or school leaving certificate is also required.' WHERE id=109 AND LENGTH(IFNULL(required_documents,''))<150;

-- #6 Ayushman Bharat PMJAY (views=182) — rd=72
UPDATE schemes SET required_documents = 'To avail treatment under Ayushman Bharat PMJAY, beneficiaries need: (1) Aadhaar Card of the household head and all family members, (2) SECC (Socio-Economic Caste Census) 2011 database verification — no separate document needed if already in the database, (3) Ration card or BPL certificate if not in SECC database, (4) Recent passport-size photograph of the beneficiary, and (5) Hospital registration documents at the time of admission. The e-card (PMJAY card) can be generated online or obtained at the nearest empanelled hospital. No advance payment is required for cashless treatment.' WHERE id=6 AND LENGTH(IFNULL(required_documents,''))<150;

-- #107 MP E-District Services (views=173) — el=117, be=96
UPDATE schemes SET eligibility = 'MP E-District Services are available to all residents of Madhya Pradesh who need government certificates and services online. Specific eligibility depends on the service being applied for: (1) Income certificate — families with annual income below the state-defined threshold, (2) Caste certificate — applicants belonging to SC, ST, OBC categories, (3) Domicile certificate — permanent residents of Madhya Pradesh for at least 5 years, (4) Birth and death certificates — events that occurred within MP. Each service has its own eligibility criteria which are verified through the respective department database.' WHERE id=107 AND LENGTH(IFNULL(eligibility,''))<150;
UPDATE schemes SET benefits = 'MP E-District Services offer the convenience of applying for 50+ government certificates and services entirely online without visiting government offices. Citizens can apply for income certificates, caste certificates, domicile certificates, birth and death certificates, marriage certificates, and many more services from the comfort of their home. The online portal allows tracking of application status in real time, and digital certificates are sent directly to the applicant registered mobile number and email. Service charges are minimal and transparent, with most certificates being issued within 7-15 working days.' WHERE id=107 AND LENGTH(IFNULL(benefits,''))<150;

-- #104 Gaon Ki Beti / Pratibha Kiran MP (views=172) — rd=98
UPDATE schemes SET required_documents = 'Applicants for Gaon Ki Beti / Pratibha Kiran Yojana in Madhya Pradesh must submit: (1) Aadhaar Card of the girl student, (2) School or college enrollment certificate from the head of institution, (3) Mark sheet of the previous qualifying examination, (4) Family income certificate below the prescribed limit issued by the competent authority, (5) Bank account passbook in the girl student name or joint with mother, (6) Caste certificate if applying under reserved category, (7) Domicile certificate of Madhya Pradesh, and (8) Recent passport-size photographs of the student.' WHERE id=104 AND LENGTH(IFNULL(required_documents,''))<150;

-- #12 PM Jan Dhan Yojana (views=170) — rd=85
UPDATE schemes SET required_documents = 'To open a Jan Dhan account, applicants need: (1) Aadhaar Card (serves as both identity and address proof), (2) One recent passport-size photograph, (3) PAN Card or Form 60 (declaration of no PAN), (4) Proof of address if not using Aadhaar — such as Voter ID, passport, or utility bill, (5) Mobile number for account alerts and OTP verification. No minimum balance is required to open or maintain the account. Family members can also open accounts; a family of up to 5 members is eligible for the scheme benefits.' WHERE id=12 AND LENGTH(IFNULL(required_documents,''))<150;

-- #105 Yuva Swarozgar Yojana MP (views=173) — el=118
UPDATE schemes SET eligibility = 'Mukhyamantri Yuva Swarozgar Yojana is open to unemployed youth who are permanent residents of Madhya Pradesh. Applicants must be between 18 to 40 years of age at the time of application. The applicant should have passed at least Class 8 (for most business categories) or Class 12 (for higher-skilled trades). Family income from all sources should not exceed Rs 3 lakh per annum. Applicants who have already received a loan under any other state or central self-employment scheme are not eligible. Priority is given to women, SC/ST, and disabled candidates.' WHERE id=105 AND LENGTH(IFNULL(eligibility,''))<150;

-- #52 Karj Mafi (views=157) — be=118
UPDATE schemes SET benefits = 'Under Mahatma Phule Karj Mafi Yojana, eligible farmers in Maharashtra receive a complete waiver of their short-term crop loans taken from scheduled commercial banks, cooperative banks, and district central cooperative banks. Loans disbursed up to Rs 2 lakh per farmer are covered under the scheme. The waiver includes both the principal amount and the accrued interest as of the cutoff date declared by the state government. Farmers who have already repaid their loans may also receive a refund of the amount paid. Over 80 lakh farmers in Maharashtra have benefited from this scheme since its launch.' WHERE id=52 AND LENGTH(IFNULL(benefits,''))<150;

-- #99 Sambal Yojana MP (views=160) — el=125
UPDATE schemes SET eligibility = 'Sambal Yojana (also known as Sambal Scholarship) is available to students who are permanent residents of Madhya Pradesh and belong to SC, ST, OBC, or economically weaker sections (EWS). Students must be enrolled in Classes 9 to 12 in a government-recognized school in Madhya Pradesh. The annual family income from all sources should not exceed Rs 1.5 lakh for SC/ST students and Rs 1 lakh for OBC students. Students must have secured at least 60% marks in the previous qualifying examination to maintain eligibility for renewal. The scheme covers both boys and girls, with a slight preference for girl students in case of tie.' WHERE id=99 AND LENGTH(IFNULL(eligibility,''))<150;

-- #98 Kisan Kalyan Yojana MP (views=167) — el=144, be=143
UPDATE schemes SET eligibility = 'Mukhyamantri Kisan Kalyan Yojana is available to all farmers registered in Madhya Pradesh who own agricultural land. Farmers must have a valid Khasra or Khatauni (land record) in their name. The scheme covers small, marginal, and large farmers equally. There is no upper income limit for eligibility. However, farmers who are also government employees or income tax assessees are not eligible. The scheme also covers tenant farmers and sharecroppers who have a valid cultivation agreement or registered lease deed in their name.' WHERE id=98 AND LENGTH(IFNULL(eligibility,''))<150;
UPDATE schemes SET benefits = 'Under Mukhyamantri Kisan Kalyan Yojana, eligible farmers of Madhya Pradesh receive financial assistance of Rs 4,000 per year per family in addition to the central PM Kisan Samman Nidhi benefit. The amount is released in two equal installments of Rs 2,000 each. The first installment is typically released before the Kharif sowing season, and the second before the Rabi season. The money is directly transferred to the Aadhaar-linked bank account of the farmer through DBT (Direct Benefit Transfer) ensuring complete transparency. Over 1.2 crore farmers in Madhya Pradesh benefit from this scheme.' WHERE id=98 AND LENGTH(IFNULL(benefits,''))<150;

-- #100 Teerth Darshan Yojana MP (views=166) — el=132, ap=153
UPDATE schemes SET eligibility = 'Mukhyamantri Teerth Darshan Yojana is available to senior citizens aged 60 years and above who are permanent residents of Madhya Pradesh. The scheme is specifically designed for Below Poverty Line (BPL) families and those with an annual income under Rs 1.5 lakh. Applicants must be medically fit to undertake pilgrimage travel. Each eligible senior citizen can be accompanied by one attendant (family member) whose travel and accommodation costs are also covered. The scheme covers all religious communities, and beneficiaries can choose from a list of designated pilgrimage destinations.' WHERE id=100 AND LENGTH(IFNULL(eligibility,''))<150;

-- #108 Old Age Pension MP (views=174) — rd=138
UPDATE schemes SET required_documents = 'Applicants for Madhya Pradesh Old Age Widow Pension must submit: (1) Aadhaar Card of the applicant, (2) Age proof certificate (birth certificate, school leaving certificate, or any government-issued document proving age 60+), (3) BPL ration card or income certificate showing annual income below Rs 50,000, (4) Bank account passbook in the applicant name with IFSC code, (5) Two recent passport-size photographs, (6) Domicile or residency certificate of Madhya Pradesh, and (7) Widow certificate (if applying under widow category) or disability certificate (if applying under disability category). Application can be submitted at the local SDM office or online through the MP Social Justice portal.' WHERE id=108 AND LENGTH(IFNULL(required_documents,''))<150;
