-- Trim meta_titles to under 60 chars for AdSense compliance
UPDATE schemes SET meta_title = 'PM Kisan Samman Nidhi 2026: ₹6,000 Farmers Scheme' WHERE id = 1 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Ayushman Bharat 2026: ₹5 Lakh Health Cover for All' WHERE id = 6 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Mahatma Phule Jan Arogya Yojana: Cashless Health Cover' WHERE id = 48 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'UP Pension Yojana: Old Age/Widow/Disability Scheme' WHERE id = 67 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Bal Shramik Vidya Yojana: Education for Workers Children' WHERE id = 71 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'UP e-District Services: Online Certificates, Apply Now' WHERE id = 62 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Swasthya Sathi WB: Cashless Health Insurance ₹5 Lakh' WHERE id = 85 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Medhavi Chatravritti Yojana: MP Scholarship Scheme' WHERE id = 102 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'UP Rojgar Abhiyan: Employment Generation in UP' WHERE id = 64 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Bihar Student Credit Card: ₹4 Lakh Education Loan' WHERE id = 73 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Sanjay Gandhi Niradhar Anudan: Monthly Pension' WHERE id = 57 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Mukhyamantri Swayam Sahayata Bhatta: UP Allowance' WHERE id = 77 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Bihar Old Age Pension: Senior Citizen Monthly Aid' WHERE id = 78 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Pratibha Kiran Yojana: Girl Education Incentive MP' WHERE id = 104 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Kanyashree Prakalpa: West Bengal Girl Child Scheme' WHERE id = 84 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'WB Student Credit Card: Education Loan ₹10 Lakh' WHERE id = 93 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Vidyarthi Mitra: Earn While Learn Maharashtra' WHERE id = 59 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'UP Kisan Karj Mafi: Farm Loan Waiver Scheme' WHERE id = 65 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'MP e-District Services: Online Certificates Apply' WHERE id = 107 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Digital Literacy Mission: Free Computer Training' WHERE id = 28 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Sarva Shiksha Abhiyan: Free Elementary Education' WHERE id = 31 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Majhi Kanya Bhagyashree: Maharashtra Girl Scheme' WHERE id = 55 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'UP Jan Arogya Yojana: Health Cover for All' WHERE id = 69 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Mahatma Phule Karj Mafi: Maharashtra Loan Waiver' WHERE id = 52 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Maharashtra Krushi Input Subsidy: Farm Equipment Aid' WHERE id = 58 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Mukhyamantri Abhyudaya Yojana: Free Coaching UP' WHERE id = 61 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Jeevika BRLPS Bihar: Rural Livelihoods SHG Mission' WHERE id = 74 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Yuvashree WB: ₹1,500/month Unemployment Allowance' WHERE id = 89 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Krishak Bandhu WB: Farmer Financial Aid & Insurance' WHERE id = 90 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'WB Old Age/Widow Pension: Monthly Social Security' WHERE id = 95 AND LENGTH(meta_title) > 60;
UPDATE schemes SET meta_title = 'Yuva Swarozgar Yojana: MP Youth Self-Employment' WHERE id = 105 AND LENGTH(meta_title) > 60;
